### ISSUE TITLE
When a workspace is idled for inactivity user is redirected to Che dashboard

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20599]
### Is your enhancement related to a problem? Please describe

Let say I'm accessing an endpoint of a workspace at 

`https://che-eclipse-che.apps.my-cluster.com/workspace<tons-of-digits>/<endpoint-name>/8080`

if my workspace is stopped, I will get like a basic 503 error (or another http error)

### Describe the solution you'd like

I would like to have a page allowing to be redirected to the dashboard to restart my workspace if the workspace is down

### Describe alternatives you've considered

Anything that may be more user friendly for the user if he refresh the editor page on a stopped workspace

### Release Notes Text

When a workspace is stopped after an inactivity now the users are redirected to the Dashboard. Previously a 503 error was displayed.

**Comment by dkwon17** [comment]
Hi, I would like to help investigate this issue

**Comment by dkwon17** [comment]
Does anyone know how this was implemented for che-server based workspaces?

I don't know how it was implemented before, but an idea I have for this issue is to use the Errors middleware https://doc.traefik.io/traefik/middlewares/http/errorpages/ to redirect requests to the dashboard when there is a 503/504 error code

**Comment by sparkoo** [comment]
@dkwon17 I would guess that behavior with che-workspaces

**Comment by dkwon17** [comment]
So far, I was able to get the middleware to sometimes work. But for it to work consistently, I have to delete the workspace service (screenshot) created in the user namespace after the workspace stops:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/83611742/167222559-64e5a235-a517-4c01-bfc8-3ce5966760cd.png">

This seems to be because the request to the service sometimes hangs for a few minutes if there are no pods, which causes traefik to close the request, preventing the errors middleware from firing:
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/83611742/167223347-6b1d94ba-e4a6-4c49-a85c-b950cf4020bd.png">

If the workspace service doesn't exist when the workspace stops, then the request to the non-existent service quickly results in an error, which the errors middleware can handle.

**Comment by dkwon17** [comment]
Hi @amisevsk , when a DW stops, would having the DWO delete the workspace service (`{workspaceID}-service`) during the DW reconciliation be reasonable?

**Comment by amisevsk** [comment]
Deleting the service would be controlled by the Che Operator, as it hosts the routing controller for the `che` routingClass. Che Operator would need to delete resources when it reconciles a DevWorkspaceRouting with the `controller.devfile.io/devworkspace-started: "false"` annotation.

Currently, DWO will clean up workspace resources (including the DevWorkspaceRouting) if it has the configuration setting `config.workspace.cleanupOnStop` set to `true`, and this may become a default behavior in the future.

**Comment by ibuziuk** [comment]
I also lean towards the middleware errors approach without changing the traefik config. 
We should be careful with the Dashboard change though, I recall it might be related to https://github.com/eclipse-che/che-operator/pull/1360/files
@olexii4 @akurinnoy wdyt?

**Comment by ibuziuk** [comment]
@dkwon17 all the PRs have been merged, can the issue be closed?

**Comment by max-cx** [comment]
sync'd to Red Hat Jira https://issues.redhat.com/browse/CRW-3181
