### ISSUE TITLE
Che workspaces fail to start with OpenShift Console samples

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20616]
### Is your enhancement related to a problem? Please describe

If I try to start a v2 devfile in Che with DevWorkspace disabled it will fail. For example [workspaces.openshift.com/#https://github.com/redhat-developer/devfile-sample.git](https://workspaces.openshift.com/#https://github.com/redhat-developer/devfile-sample.git).

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/606959/136627809-e276f80f-31a7-42be-93b2-e503581343ad.png">

That's problematic because OpenShift developer console has 4 examples with a devfile v2 at its root:

![image](https://user-images.githubusercontent.com/606959/136629378-c48d6d19-1856-4092-a08a-e19dff2ebf99.png)

And those will fail to fail to open in Che when using OpenShift Developer Console topology link

<img width="363" alt="image" src="https://user-images.githubusercontent.com/606959/136628766-1f33b74b-1161-4f6d-aba7-d221683d3238.png">

### Describe the solution you'd like

In the very short term, when DW **is not** enabled but the che-server returns a **v2** devfile.yaml, we should use devfile v2 to v1 conversion lib used by Che-Theia. 
- [x] https://github.com/eclipse/che/issues/20644

In the long term, for those these 3 cases:

- if DW **is** enabled but the che-server returns a v1 devfile.yaml
- if che-server consider the devfile invalid
- if che-server cannot validate becuse the specVersion is not supported

warn the user (with a clear message that specifies that the problem is one of 3 above, a link to the problematic devfile and the possible workarounds) and ask if he prefers to interrupt workspace startup (and eventually fix the devfile) or discard the devfile content and move forward with the creation of the workspace.

**Comment by sleshchenko** [comment]
> If schema is valid v2 and DW is not enabled: start a workspace as if there was no devfile

well, I think the right solution here would be Florent's proposal, where we scan the repo and respect devfile.yaml, devfilev1.yaml depending on Che mode.
Applying empty devfile does not solve the issue in the flow but makes it less visible. In the end user's won't get IDE that will work well for their project.

>  If schema is invalid: start a workspace as if there was no devfile

I do not really agree with that.
If we take a deeper look on the cause: it's the issue that may appear because ODO/OpenShift console depends on one devfile v2 schemaVersions, and Che embeds itsown.
the proposed solution just hides the issue but don't solve it. The solution would be making Che Server depends on some central Schema provider to evaluate if schema is valid or not, the same could you ODO or OpenShift Console.

Anyway, I would not mix these issues together.

**Comment by benoitf** [comment]
And tests there https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts

**Comment by l0rd** [comment]
I am raising it as a blocker for next week release as this make Che (and CRW) unsuable with a few samples in OpenShift. cc @nickboldt @RickJWagner  @mbenitez1607

**Comment by dmytro-ndp** [comment]
@l0rd, @rhopp, @musienko-maxim: dedicated test case "_start-dw-with-OpenShift-console-samples_" have been added into the [CRW 2.13.0 Test plan](https://docs.google.com/spreadsheets/d/1BWZc5NbqQzkkRez1ceokwsAA6GFAK5fEQ-YjVDKrUCc/edit?usp=sharing).

**Comment by l0rd** [comment]
Closing this issue as the orignal problem (supporting v2 devfiles when `devWorkspaceEnabled: false`)  has been addressed. A generic solution to handle unsupported devfiles versions is tracked by https://github.com/eclipse/che/issues/20738
