### ISSUE TITLE
When admin switches the engine to DevWorskpace all che-server based workspaces should be stopped

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20631]
### Describe the bug

- install 'eclipse-che' using the stable channel
- create CR with a single-host and OpenShift Auth enabled 
- create an account (using 'developer' OpenShift account on the crc for example) with a couple of workspaces and start one of them
- wait until workspace is running, run build / run command
- update the CR from the `eclipse-che` namespace and enable devWorkspace
```
  devWorkspace:
    enable: true
```
- go back to the running workspace - UD does not show it anymore, however workspace pod is still running
- ERROR: previously running workspace pod is still running, even though UD does not show it 

### Che version

7.37@latest

### Steps to reproduce

- install 'eclipse-che' using the stable channel
- create CR with a single-host and OpenShift Auth enabled 
- create an account (using 'developer' OpenShift account on the crc for example) with a couple of workspaces and start one of them
- wait until workspace is running, run build / run command
- update the CR from the `eclipse-che` namespace and enable devWorkspace
```
  devWorkspace:
    enable: true
```
- go back to the running workspace - UD does not show it anymore, however workspace pod is still running
- ERROR: previously running workspace pod is still running, even though UD does not show it 

### Expected behavior

When admin switches the engine to DevWorskpace all che-server based workspaces should be stopped

### Runtime

OpenShift

### Screenshots

When admin switches the engine to DevWorskpace all che-server based workspaces should be stopped

### Installation method

OperatorHub

### Environment

Linux

**Comment by ibuziuk** [comment]
PR has been merged https://github.com/eclipse-che/che-server/pull/177
Closing

**Comment by nickboldt** [comment]
So with this change, once a CRW instance is updated from 'latest' (no DW) to 'all-namespaces' (DW enabled)...

* existing workspaces are stopped

How does a user restart the workspace? Will it be automatically converted to v2.1 for them?

Or, will they have to manually fix things, in one of two ways:

a) manually update the devfile in the dashboard editor to upgrade it to v2.1 (and then commit these changes back to their source repo so changes are persisted)

b) open a NEW workspace from the existing devfile via the factory URL, and have it converted for the user automatically... then user needs to remember to commit the updated devfile back to the source repo so the converted version 2.1 flavour instead of the now-obsolete 1.0 flavour is kept and can be reused.

Are those the correct user stories?

**Comment by dmytro-ndp** [comment]
@nickboldt : there is an issue about further actions: https://github.com/eclipse/che/issues/20845
