### ISSUE TITLE
Investigate memory consumption of che-operator with growing number of namespaces on the cluster

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#20647]
### Is your task related to a problem? Please describe

`che-operator` pod is OOMKilled when there are a lot of namespaces on the cluster.
It has been fixed by [1] but still I can observer that operator consumes too much memory.
We have to find the reason and fix it.

[1] https://issues.redhat.com/browse/CRW-2383
[2] https://github.com/eclipse-che/che-operator/pull/1146

### Describe the solution you'd like

N/A

### Additional context

https://github.com/devfile/devworkspace-operator/issues/616
https://github.com/eclipse/che/issues/20529

### Release Notes Text

Title: Improved operator memory consumption
Content: Fixed an operator issue that forced to augment the memory requirement based on the number of the namespaces on the cluster.

**Comment by tolusha** [comment]
Don't close issue until doc is ready

**Comment by mmorhun** [comment]
The problem was in caches that's managed by Controller Runtime framework used in Che Operator. It caches all objects of the kind if the operator gets at least one object. It had been worked fine, but when Che Operator was switched to watch all namespaces (this PR) it started to cache all objects in cluster. We spot the bug only on a big cluster.
To fix the issue we limit set of objects that the Operator caches. However, it is not possible to control caching of every single object as Controller Runtime framework doesn't allow it. Instead, it is possible to define a selector for each kind of objects that should be cached. To reach that we need a label on each object of kind we limit cache for (we do it for all standard kinds like deployment, service, etc., and do not need the label for namespaces and all CRs).
The label that should be present on all objects Operator interacts with is `app.kubernetes.io/part-of=che.eclipse.org`.
After applying the fix, the memory usage for ~5000 namespace cluster dropped from ~1.2 GiB (with peaks to ~3.3 GiB) to just ~ 30 MiB:

![Screenshot from 2021-11-16 12-41-21](https://user-images.githubusercontent.com/15607393/141970865-fab19383-5eb8-4fa1-aa35-0f850b90d460.png)

Also, migration is implemented, so update should be seamless for existing Che installations.

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2549
