### ISSUE TITLE
[devworkspace-che-operator] devworkspaces fail if multple che controllers in cluster

### ISSUE THREAD

**Issue by guydog28** [eclipse/che#20704]
### Describe the bug

We have two che installations in our kubernetes cluster - one where we test new features and one that is being used by the team.  In testing devfile v2, we determined that che-operator only installs one devworkspaces namespace/controller, and then when the second che installation was added, that devworkspaces controller didnt know which operator to use.  Error:

**Unable to provision networking for DevWorkspace: workspace routing is invalid: the routing does not specify any Che manager in its configuration but there are 2 Che managers in the cluster**

### Che version

7.38@latest

### Steps to reproduce

1. Install Che (operator)
2. enable devworkspaces, verify "working"
3. Install 2nd Che to new namespace
4. enable devworkspaces in 2nd che 
5. verify both are now not working when launching a workspace with the error above.

### Expected behavior

Either there should be two distincy devworkspaces installations, one per cluster (better for testing which is our setup here), or che needs to send more information about itself to devworkspaces controller to help setup networking.

I know that kubernetes (not openshift) isn't fully supported yet, but i wanted to get this in so it can be added to a milestone.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by svor** [comment]
@amisevsk could you take a look please

**Comment by tolusha** [comment]
It is not supported to have several Eclipse Che deployments on the same cluster.

**Comment by amisevsk** [comment]
The DevWorkspace Operator is designed to watch all namespaces (a requirement since workspaces can appear anywhere); the downside of this is that only one instance of the controller can run on the cluster (otherwise they fight over who reconciles each object, often resulting in a loop). The coming release of DWO should detect this issue on startup and fail to start a second instance, but DWCO may need to be adapted to address this as well (don't deploy DWO if DevWorkspaces are available already)

I'm not fully familiar with the details of how DevWorkspace Che operator works, so the pieces below may be somewhat inaccurate.

I suspect a similar issue is occuring for the DevWorkspace Che Operator as well, as (I believe) the controller that reconciles routing for DevWorkspaces watches all namespaces. The DevWorkspace Operator has functionality to propagate annotations down to the DevWorkspaceRouting (see (`RoutingAnnotationInfix`)[https://github.com/devfile/devworkspace-operator/blob/6be1bdb93bba173b0a12683bdbd547b85e63b173/pkg/constants/metadata.go#L78-L80]), which could be used to partition DevWorkspaces based on which instance of Che created them. For example, it should work to use
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    - che.routing.controller.devfile.io/instance: "some-hash"
  name: example-devworkspace
```
and then only reconcile DevWorkspaceRoutings if the hash matches on the DevWorkspaceRouting. The flow would be something like

1. Che creates DevWorkspaces with the annotation above for some persistent, unique hash (how to do this is unclear)
2. The DevWorkspace Operator propagates the annotation to the DevWorkspaceRouting.
3. The Che Operator ignores objects that do not have a matching annotation.

However, this would be a pretty large-scale change to how things work.
