### ISSUE TITLE
[devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the separate container

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#20787]
### Describe the bug

Java-Mysql sample does not work in devworkspace.
The sample tries to connect to mysql by uri `jdbc:mysql://localhost/petclinic`, but seems the host with mysql is not recognized as localhost.
The same sample works fine on local minikube deployment (and on other dev clusters).

### Che version

7.39@latest

### Steps to reproduce

On devworkspace:
1. create workspace using https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
2. open `/projects/java-spring-petclinic/src/main/resources/db/mysql/data.sql`, go to first row for table `owners` and replace values on `test` (screenshot 1)
3. navigate to `My Workspace` view on the right and run `prepare-database` command
4. build the sample by running `build` command from `My Workspace` view or by opening a terminal in `tools` container and launching `mvn clean install`
5. Use `mvn spring-boot:run -Dspring-boot.run.profiles=mysql` command to run the samle

Check the output, be sure `mysql` profile is using (screenshot 2)

6. At this step, the sample will fail with error
`com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure` 
(screenshot 3)

### Expected behavior

Running sample as on screenshot 4.

### Runtime

minikube

### Screenshots

- screenshot 1
![Screenshot from 2021-11-17 15-56-07](https://user-images.githubusercontent.com/1655894/142215264-ada74db0-97d3-44ca-84d0-bb7a7b6113a0.png)

- screenshot 2
![Screenshot from 2021-11-17 16-09-27](https://user-images.githubusercontent.com/1655894/142216047-7fc719e6-fadd-4e0c-8129-7e4e3a749189.png)

- screenshot 3
![Screenshot from 2021-11-17 16-17-52](https://user-images.githubusercontent.com/1655894/142217506-2a57a7ce-5c97-471b-8cae-e9f39050508c.png)

- screenshot 4 (working sample, workspace was created using devfile v1)
![Screenshot from 2021-11-17 16-19-42](https://user-images.githubusercontent.com/1655894/142217719-afe5b3f5-487c-4371-8521-dd4017a04438.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by benoitf** [comment]
is that https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/devfile.yaml#L34 changed to internal is changing something ?

**Comment by svor** [comment]
@benoitf the same result:
![screenshot-che-eclipse-che apps cluster-ttxw6 ttxw6 sandbox46 opentlc com-2021 11 17-20_55_47](https://user-images.githubusercontent.com/1271546/142264773-ec1f9c0b-eaf9-4038-aac2-63b3e6c8a287.png)

**Comment by benoitf** [comment]
Hello,

so I reproduced the problem but the caused by is
```
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```

It's about a deprecation on TLS
https://www.oracle.com/java/technologies/javase/11-0-11-relnotes.html#JDK-8202343
https://aws.amazon.com/blogs/opensource/tls-1-0-1-1-changes-in-openjdk-and-amazon-corretto/

In main branch, devfile is using a che-java image using Java 11.0.10 while in Universal Developer Image java version is 11.0.12 which has the deprecated TLS removed

Also for MySQL we should update MySQL to a more recent version
current version used in devfile is
```
bash-4.2$ mysql --version
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper
```
it's from 2018 !
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-24.html

As upgrading to a more recent version like 5.7.36, we could also take the opportunity to use a multi-arch image

And maybe use https://hub.docker.com/_/mariadb?tab=tags that is a drop-in replacement of MySQL

or any other solution
