### ISSUE TITLE
Resizing terminal tab is messing up the content of quarkus:dev

### ISSUE THREAD

**Issue by apupier** [eclipse/che#20806]
### Describe the bug

- start a quarkus ap pin dev mode `mvn quarkus:dev` in a terminal
- try resizing the terminal tab
- the content is messed up

### Che version

7.36

### Steps to reproduce

- start a quarkus ap pin dev mode `mvn quarkus:dev` in a terminal
- try resizing the terminal tab
- the content is messed up

### Expected behavior

the terminal contetn displays the correct infomration at the correct lines

### Runtime

OpenShift

### Screenshots

![messedUp-terminaloutput-onresize](https://user-images.githubusercontent.com/1105127/142871002-4295ab31-a397-441d-912e-05a678c380a6.gif)

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by ibuziuk** [comment]
@azatsarynnyy could you please take a look?

**Comment by azatsarynnyy** [comment]
Probably, it's because the last line (`Press [r] ...`) is pinned (not scrolled).
It looks like another Xterm issue. There are several ones already registered in upstream Theia, e.g. https://github.com/eclipse-theia/theia/issues/10093
Upgrading the Xterm version may help. But it's not planned for the nearest future.
