### ISSUE TITLE
Build and publish multi-platform developer images

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20862]
### Is your enhancement related to a problem? Please describe

We are currently only building `linux/amd64` [developer images](https://github.com/devfile/developer-images).

### Describe the solution you'd like

- Identify supported platforms for every tool included in the image and add specify it in a devtools.json file
- Adapt the asset build/download script to only process the tools that are supported on current platform
- Use [gh docker build push action](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) to build and push `linux/amd64`, `linux/arm64`, `linux/ppc64le` and `linux/s390x` versions of the images.

**Comment by nickboldt** [comment]
For downstream developer images (UDI) see https://issues.redhat.com/browse/CRW-2463 and https://issues.redhat.com/browse/CRW-2464 (requires https://github.com/eclipse/che/issues/19953 )

If upstream is not multiarch (because we can't use buildx on Z) that should not prevent downstream from being multiarch.

**Comment by nickboldt** [comment]
Downstream no longer has to split between TP and GA as we have added labels into the dashboard. There are also no openj9 images anymore. So while we still need multiarch downsteam, the same Dockerfile might be possible for up and downstream. 

We might still filter out some languages that are not supported downstream.
