### ISSUE TITLE
[devworkspace] Impossible to start the workspace after updating the devfile, using che-theia::k8s-devfile-service

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#20910]
### Describe the bug

At the moment Che-Theia Plugins panel is only way to easily install a plugin https://github.com/eclipse/che/issues/20638
It requires to be able to update the devfile, using k8s implementation of devfile service.

After calling k8s-devfile-service::update(..), the devfile being to be updated and the workspace is restarted automatically.
![Screenshot from 2021-12-09 17-35-25](https://user-images.githubusercontent.com/1655894/145472322-4bf6e3a5-8499-4405-8c45-337fce938a14.png)

But it appeared, that it's not possible to start the workpsace again, due to following error

![Screenshot from 2021-12-09 17-35-48](https://user-images.githubusercontent.com/1655894/145472294-028e3908-9145-4888-b9fe-89340d38fd59.png)

### Che version

next (development version)

### Steps to reproduce

1. Create a workspace using https://github.com/vitaliy-guliy/java-spring-petclinic/tree/devfilev2
2. Open plugins view, install any che-plugin, that is running int the separate sidecar ( try asciidoctor plugin )

Workspace will be stopped and then failed when restarting.

### Expected behavior

Running workspace.

### Runtime

minikube

### Installation method

chectl/latest, chectl/next

### Environment

Linux

**Comment by ibuziuk** [comment]
@amisevsk could you please take a look?

**Comment by amisevsk** [comment]
This looks like an issue in how Theia is handling updating the DevWorkspace on-cluster. There are two resources Theia can look at, which are accessible through the env vars:
* `$DEVWORKSPACE_ORIGINAL_DEVFILE` is the path to a file representing the DevWorkspace's `.template.spec` as it appears *on the cluster*. This is the resource that should be applied to the cluster when modifying the running DevWorkspace
* `$DEVWORKSPACE_FLATTENED_DEVFILE` is the path to a file representing the processed DevWorkspace's `.spec.template` as seen by DWO internally (i.e. with all plugins/parents resolved). This is the resource that should be used to determine endpoints, etc., as those can be added by plugins and so are not explicitly in `DEVWORKSPACE_ORIGINAL_DEVFILE`.

It looks like what's happening is Theia is modifying `$DEVWORKSPACE_FLATTENED_DEVFILE` and applying that to the cluster, which is incorrect. Doing this will also disconnect the DevWorkspace definition from any plugins currently imported (e.g. the Theia DWT). 

I've created https://github.com/devfile/devworkspace-operator/issues/709 to try address a part of this on the DevWorkspace side, but the underlying issue is due to how the DevWorkspace is being updated.

**Comment by amisevsk** [comment]
/remove-lifecycle stale

Should be confirmed whether this is resolved or not.
