### ISSUE TITLE
[theia-devworkspace handler] Add parameter to configure registry and tag in DW templates

### ISSUE THREAD

**Issue by svor** [eclipse/che#20967]
### Is your task related to a problem? Please describe

It should be possible to configure registry and tag in generated DevWorkspace templates 

### Describe the solution you'd like

Add parameters like:  
  --tag, -t [TAG]
        Docker image tag to be used for image; default: 'next'
    --registry, -r [REGISTRY]
        Docker registry to be used for image; default 'quay.io'

**Comment by nickboldt** [comment]
Changing the registry won't help w/ CRW/whitelabelling, since the entire image is different...

- [ ]           quay.io/eclipse/che-theia@sha256:ebcc893364c233f4ebbaef61c6b2027c2aabecf05844f6151837dbb13193480d
- [ ]           quay.io/eclipse/che-machine-exec@sha256:2ecefe3a93c1ce35b0d56beb150a8d4c18330a967fedfe00fd073a5f0ac95b8b
- [ ]           quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:79df39dcc1bc37503a94303a25e1eabc985ce820d552d16a4b85ec444a7b2b1f

Also not sure how these will work in airgap... are we caching them inside the container somehow?

```
che-theia.eclipse.org/vscode-extensions:
            - >-
              https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.82.0-369.vsix
            - >-
              https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix
            - >-
              https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix
```

**Comment by svor** [comment]
it seems it could be configured by `pluginRegistryUrl` parameter https://github.com/eclipse-che/che-theia/blob/main/tools/devworkspace-handler/src/main.ts#L30-L32
