### ISSUE TITLE
Drop backup and restore functionality

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21006]
### Is your task related to a problem? Please describe

Backup/Restore currently is flaky and it is not work with DevWorkspace engine.
It is better to remove it for a while not to frustrate customers.

### Describe the solution you'd like

Remove API and CRDs

**Comment by ibuziuk** [comment]
@tolusha could you please confirm that backup and restore will still work correctly in CRW 2.14 / 2.15 (che-server engine). This functionality is crucial for https://issues.redhat.com/browse/CRT-1415 
Basically, the plan is to backup operands from the addon namespace and restore in the newly created `crw` namespace (there is a tech requirment for having CRW, WTO, DWO running in the same namespace)

**Comment by dmytro-ndp** [comment]
@ibuziuk: neither backup-restore nor rolling update work in 2.14.0 with che-server engine: https://issues.redhat.com/browse/CRW-2621, https://issues.redhat.com/browse/CRW-1497

**Comment by dmytro-ndp** [comment]
@ibuziuk: an update: it turned out that backup / restore worked in CRW 2.14.0.
CRW 2.14.0 backup had failed on OCP with leftovers from DevWorkspace, installed on the same OCP earlier [1].

[1] https://issues.redhat.com/browse/CRW-2621?focusedCommentId=19599679&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19599679
