### ISSUE TITLE
How should Eclipse Che instances installed on K8s via Operator Hub upgrade past 7.39.2?

### ISSUE THREAD

**Issue by virtuakazib** [eclipse/che#21161]
### Summary

As of version 7.40, Eclipse Che is no longer releasing updates through Operator Hub for Kubernetes clusters.  So for current Eclipse Che instances installed on Kubernetes through Operator Hub, what is the best way to upgrade Eclipse Che past 7.39.2?

**Comment by tolusha** [comment]
@virtuakazib 

I can suggest the following way (needs to be carefully checked):
* uninstall operator from the operatorhub
* create operator deployment https://github.com/eclipse-che/che-operator/blob/7.39.2/config/manager/manager.yaml
* install chectl 7.41.2 https://github.com/che-incubator/chectl/releases/tag/7.41.2
* run `chectl server:update`

NOTE:  You can't update to 7.42.0 and higher version since it is not backward compatible.

**Comment by tolusha** [comment]
That's architectical changes. We switched to the new workspace engine.
Some doc https://www.eclipse.org/che/docs/che-7/administration-guide/architecture-overview-with-devworkspace/

There is a migration guide, but not published yet.
https://github.com/eclipse-che/che-docs/pull/2159

**Comment by virtuakazib** [comment]
Thank you.
