### ISSUE TITLE
what is the default password for root user in the workspace terminal?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21217]
### Summary

After launching [a project](https://github.com/spring-projects/spring-petclinic.git) in my workspace, i clicked `tools` -> `New terminal` 

The `terminal` appeared in the editor. i wanted to explore more by logging in as `root`. But i'm not aware of the `password`. Please let me know how to login as `root` user here. What is the `default password`?

![image](https://user-images.githubusercontent.com/10482177/155494441-6a4748d5-a399-4e72-b333-c0f0fd7ef191.png)

The operating system details are below
![image](https://user-images.githubusercontent.com/10482177/155494955-cd9458f7-bf42-482b-b5b9-d5be70aba0d7.png)

**Comment by ibuziuk** [comment]
Hello, Eclipse Che workspace is a set of containers running as a pod on the kubernetes infrastructure.
In general, containers running as root is a significant security risk + containers are supposed to be immutable, and installing anything inside the container is not recommended since after the restart all the packages will vanish. What is more some of the infrastructures do not support sudo and workspace containers are running using the [Arbitrary User IDs](https://docs.openshift.com/online/pro/creating_images/guidelines.html#use-uid) (This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node).

Could you clarify the use case for sudo? Basically, using sudo could be treated as an anti-pattern in the containers world.

**Comment by Divine1** [comment]
@ibuziuk thank you for the details. i have no usecase that will require sudo. i was just exploring the terminal in `eclipse-che`.

have a great day
