### ISSUE TITLE
User guide - Mounting volumes, secrets, and configmaps

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21299]
### Is your enhancement related to a problem? Please describe

User Guide needs to be updated ([global issue](https://github.com/eclipse/che/issues/21285)). This issue is about the creation of a new "Mounting volumes, secrets and configmap" section.

### Describe the solution you'd like

This is about getting the content from:
- former user guide / using developer workspaces / mounting a secret as a file
- former user guide "Authenticating users on private repositories of SCM servers"
- DevWorkspace operator [automount doc](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.md#automatically-mounting-volumes-configmaps-and-secrets)
and adapt/merge it together.

If that's not cover yet we should also talk about how a user can specify its container registries credentials.

**Comment by max-cx** [comment]
@l0rd, looks like the second bullet point, `former user guide "Authenticating users on private repositories of SCM servers"`, here also falls under https://github.com/eclipse/che/issues/21298.

My personal suggestion is, if @amisevsk hasn't started working on it yet, and if @dkwon17 has the bandwidth for it, to move this bulletpoint to https://github.com/eclipse/che/issues/21298 and ask **dkwon17** to do this because **dkwon17** has now a fresh overview of Git-related procedures. One more benefit of **dkwon17** working on this is figuring out the outline for Git-related pages in the user guide.

Any thoughts on this, anyone?

**Comment by max-cx** [comment]
@l0rd, can you please to clarify what the second bullet point here, `former user guide "Authenticating users on private repositories of SCM servers"`, is in the user guide of the old docs:

Is it
(**A**) https://www.eclipse.org/che/docs/che-7/end-user-guide/authenticating-on-scm-server-with-a-personal-access-token/
or
(**B**) https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_che
or
(**C**) something else (and if so, then what it is)
?

BTW, I've opened a PR on a similar topic, but that's for the Admin Guide: https://github.com/eclipse-che/che-docs/pull/2271

**Comment by l0rd** [comment]
My second bullet point is about **(A)**
**(B)** instead is part of the article that I refer in my first bullet point

**Comment by dkwon17** [comment]
Hello @amisevsk , sorry, I already made a PR to update **(B)** that I've tested and verified myself: https://github.com/eclipse-che/che-docs/pull/2275 since I thought **(B)** was also a part of https://github.com/eclipse/che/issues/21298 

If you were already working on it, I can close my PR.
