### ISSUE TITLE
Allow to boot a workspace in rescue mode

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21335]
### Is your enhancement related to a problem? Please describe

sometimes we have our devfile being corrupted by manual changes. Also it may be corrupted after a devfile v1-> v2 step.

I think having a resuce mode to be able to go back to the workspace and being able to browse files/eventually commit the files would help for some usecases.

### Describe the solution you'd like

Allow to boot a workspace in a `rescue` mode.

It'll use for example the current universal developer image and default stable editor.

It could be done either from dashboard side only or devWorkspace could have an extra attribute like `rescue`.

Original content could be wrapped into an attribute (if we want to switch back to the previous workspace)

### Describe alternatives you've considered

It could be a temporary workspace taking the same `id` of the original one so volume is mounted.

### Additional context

with devfile v1--> v2 migration some workspaces may not be able to be converted automatically

**Comment by amisevsk** [comment]
Since a "rescue" mode in DWO would require bundling additional images (what image do we use for the rescue component?), this makes more sense as a dashboard feature, IMO. This is also potentially impacted by dashboard's processing of the devfile (e.g. injecting an editor).

Manually, the process would be to 
1. Remove all container components from the devfile
2. Add some known component (e.g. a basic CLI image, maybe the web-terminal-tooling image?) that mounts all of the volumes in the devfile
3. Do what's needed to save work, etc.

Alternatively, it should be sufficient to add a feature to "reset" a devfile, replacing the devfile components with a standard configuration based on the stack -- e.g. It'd be nice if I could "reset" my devfile to the default Java-springboot devfile to undo any changes. This would be especially useful with https://github.com/eclipse/che/issues/21244
