### ISSUE TITLE
When a devfile is not present Che should include a UDI based dev container in the workspace

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21340]
### Is your enhancement related to a problem? Please describe

Today in https://github.com/eclipse/che/issues/20705 we have the ability to autoload a default v2 devfile when none is present in the git project's repo. Cool beans.

However, if the project needs build tools, like the ones provided by the UDI sidecar, none will be present until the user customize the workspace components.

So... while it's great we can load a project for any git repo, it's of limited usefulness if we can't then compile/run/test/debug the code.

### Describe the solution you'd like

OOTB when no devfile is present, the default devfile should include the Che or Dev Spaces UDI image as an available sidecar, so users can open a terminal in that container and at least run build commands (java, javac, mvn, gradle, python, etc.)

As in all things Che, this functionality needs to be whitelabel'd/skinnable/extensible so it can easily be configured to load a DIFFERENT default UDI image.

### Describe alternatives you've considered

Document how to write your own devfiles and while generating a default devfile with no build environment, open a README in the workspace saying "so we opened your project, but since you don't define a devfile, we can't know what compilation environments you might want. Here's the boilerplate code to add the UDI sidecar to your generated devfile. Once updated, please save your changes, close the workspace, and reload it from the updated project w/ the devfile in it."

It puts the effort onto the user so the OOTB experience is more manual work, but it saves the effort for the dev team to include the UDI image in the default devfile. 

### Additional context

Subtasks:
- devfile/devworkspace-operator/issues/656
- eclipse/che/issues/21354
- eclipse/che/issues/21353

**Comment by l0rd** [comment]
Rather than leverage `cheFlavor` we should introduce a `workspaces.defaultDevContainerImage` property in `CheCluster` CRD. The default value will be `quay.io/devfile/universal-developer-image` for Che.

**Comment by l0rd** [comment]
Also note that [to introduce a `defaultDevComponent`](https://github.com/eclipse/che/issues/21340#issuecomment-1103634754) there are a couple of preliminary issues to address:

**We should support only one way to inject an editor**

Currently Theia runs in its own sidecar whereas VS Code is injected in the dev component. The consequence is that in a no-devfile scenario the behavior is different based on the editor:
- if the editor is Theia: the workspace is started and the dev container is Theia container
- if the editor is VS Code: the workspace fails to start because no dev container has been specified

Rather than supporting both scenarios we should:
- [ ] Inject Theia in the dev component of a devfile by default (as we do with VS Code)
- [ ] Use an attribute to specify the Devfile component where the editor will be injected (if there are more than one component)

**Editors spec should allow to override devComponent properties**

Theia has some pre-requisites (env variables, endpoints, memory, cpu etc...) and VS Code has it's own. We want to let developers to choose their editor but we want to have one unique `defaultDevComponent`:

- [ ] https://github.com/devfile/devworkspace-operator/issues/656

**Comment by benoitf** [comment]
Note that the default component if missing is defined for Che Code editor there: https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L502-L551

It should be handled by https://github.com/devfile/devworkspace-operator/issues/656

**Comment by nickboldt** [comment]
Closing as this works downstream in 3.3 based on Mario's tests.
