### ISSUE TITLE
API requests to che-server are stateful and require cookie

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21419]
### Is your task related to a problem? Please describe

Steps to reproduce:

1. get user access token `useroauthaccesstokens`
2. execute the API request to che-server using one of the tokens e.g. `curl -H "Authorization: Bearer sha256~<>" 'https://<che-host>api/user`
3. ERROR: request is failing and returns `Log in with OpenShift` page

### Describe the solution you'd like

API request return valid date when valid user access token is provide

### Describe alternatives you've considered

Swagger API works since the valid cookie exist 

### Additional context

Due to this bug it is not possible to automate any of the requests to che-server

**Comment by sparkoo** [comment]
To clarify what is happening there (at least what I think is happening). When request reaches che service, it first hits oauth-proxy. This will make sure that request is authenticated by checking authentication cookie. With curl, there is no cookie so it will redirect to login page. With swagger it will work, because you're required to login first and the cookie is stored in the browser and send together with request by swagger.

oauth-proxy is currently configured that it does not accept token in authorization header. I believe we need to configure it with `--openshift-delegate-urls` (https://github.com/openshift/oauth-proxy#delegate-authentication-and-authorization-to-openshift-for-infrastructure) so it accepts also token in authorization header and authorize it against openshift api. I've never played with this, so I'm not sure about exact behavior. oauth-proxy configuration is set by che-operator https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/gateway/oauth_proxy.go#L53. Be aware, that kubernetes and openshift deployments uses different oauth-proxy versions with different configuration. This fix won't work directly on kubernetes.

There should be nothing needed for che-server.

**Comment by luxingxiao** [comment]
> To clarify what is happening there (at least what I think is happening). When request reaches che service, it first hits oauth-proxy. This will make sure that request is authenticated by checking authentication cookie. With curl, there is no cookie so it will redirect to login page. With swagger it will work, because you're required to login first and the cookie is stored in the browser and send together with request by swagger.
> 
> oauth-proxy is currently configured that it does not accept token in authorization header. I believe we need to configure it with `--openshift-delegate-urls` (https://github.com/openshift/oauth-proxy#delegate-authentication-and-authorization-to-openshift-for-infrastructure) so it accepts also token in authorization header and authorize it against openshift api. I've never played with this, so I'm not sure about exact behavior. oauth-proxy configuration is set by che-operator https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/gateway/oauth_proxy.go#L53. Be aware, that kubernetes and openshift deployments uses different oauth-proxy versions with different configuration. This fix won't work directly on kubernetes.
> 
> There should be nothing needed for che-server.

I have a che cluster instance version 7.50 and how to config oauth_proxy to use bearer token but cookie.
