### ISSUE TITLE
Can't opt out of giving Che OAuth access to GitHub, even for public repos

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21436]
### Describe the bug

Since https://github.com/eclipse-che/che-server/pull/301, Che will always prompt for OAuth access and use this if granted to simplify user setup. However, Che will refuse to start workspaces from public GitHub repos unless full read/write access is granted, even for public repos. If a user doesn't want to grant this access to Che, the workspace start fails with a plaintext page that says
```
Authentication failed: access_denied
```

### Che version

next (development version)

### Steps to reproduce

1. Attempt to open factory url from github, e.g. https://github.com/che-samples/golang-example/tree/devfilev2

### Expected behavior

If OAuth isn't granted, Che should fall back to an unauthenticated flow.

### Runtime

OpenShift

### Screenshots

![che-oauth-flow](https://user-images.githubusercontent.com/16168279/171272631-01889fa7-7a18-42a8-9f90-f3a79b3e8cd7.gif)

### Installation method

OperatorHub

### Environment

Linux

### Additional context

Original issue: https://github.com/eclipse/che/issues/21346

**Comment by benoitf** [comment]
Hello, setting as P2 for now.
Note sure how to handle the bug. Because I assume https://github.com/eclipse/che/issues/20583 means that if oAuth is there then you need to accept the privileges to continue.
The whole story is to be authenticated as soon as you're using the product using oAuth.

cc @l0rd for adjusting the priority
