### ISSUE TITLE
Automate workspace startup verification against the airgap Openshift cluster

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21445]
### Is your task related to a problem? Please describe

A periodic nightly job that:
- creates the 4.10 airgap cluster
- installs the nightly version of Eclipse Che 
- starts the workspace
- wait till the workspace is in the running state
- execute the build command

### Describe the solution you'd like

probably we should start the automation with the `che-code` based workspaces

**Comment by tolusha** [comment]
Outdated Jenkins job
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Che/job/e2e/job/ocp/job/complex/job/disconnected/job/disconnected-deploy/

**Comment by dmytro-ndp** [comment]
Old pipeline script to fix: 
- https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/4c24a7e0eb866bf2c50bb74ea8b84c96ec8939bf/jobs/Che/e2e/ocp/complex/disconnected/disconnected-deploy.groovy
- https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/4c24a7e0eb866bf2c50bb74ea8b84c96ec8939bf/jobs/Che/e2e/ocp/complex/disconnected/disconnected-deploy.jenkinsfile

In order to respect our resources limitations, please, use dedicated AWS account, or dedicated Single Node airgap OCP on CRW AWS account, just for Eclispe Che testing.

**Comment by tolusha** [comment]
https://github.com/openshift/release/pull/33476

**Comment by ibuziuk** [comment]
@tolusha is the issue still relevant?

**Comment by tolusha** [comment]
It is blocked by https://github.com/eclipse/che/issues/21994

**Comment by amisevsk** [comment]
#21994 should be resolved now.

**Comment by tolusha** [comment]
https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/1658
