### ISSUE TITLE
When starting a workspace with the same name as an existing one ask users if they wants to replace the pre-existing one

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21561]
### Describe the bug

Getting Started workspace fails to start if there is an existing workspace

### Che version

7.50@latest

### Steps to reproduce

![existing workspace](https://user-images.githubusercontent.com/1461122/179742214-a058abb5-022d-47b6-ae9d-1815dbc23b74.gif)

### Expected behavior

exising cpp workspace is started 

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

### Additional context

Note Dashboard should reopen any workspace if exists not only Getting Started 

### Release Notes Text

Previously, when starting a workspace with the same name of an existing one, Che would return an error and users should either manually delete the existing one or rename the new workspace. Now users are asked if they want to re-open the existing one or if they want to replace it with the new workspace.

**Comment by ibuziuk** [comment]
the issue is really annoying and we should backport the fix in 3.2

**Comment by l0rd** [comment]
Ok but we should not restart the workspace because it has the same name: it may have the same name but refer to another branch (i.e. you have just reviewed a PR) or even be a completely different git repository. How are we going to figure out if that's the same workspace or a different one?

**Comment by svor** [comment]
Can we just create a new workspace but with another name (maybe adding some suffix)

**Comment by l0rd** [comment]
> Can we just create a new workspace but with another name (maybe adding some suffix)

Right but that's what `generateName`, in the DevWorkspace spec, is supposed to do. If the problem here is with samples I think we can use [generateName](https://github.com/devfile/api/blob/main/schemas/latest/dev-workspace.json#L51) instead of `name` when generating the DevWorkspace.

I think samples are easy because we start from a `DevWorkspace.yaml`. @ibuziuk the problem here is with a sample (i.e. if fails the second time you try a sample) right?

I can create a distinct issues for non-samples but in general I would ask the user if he wants to restart the existing workspace or replace it with the new one. To create multiple workspace using the same devfile it's recommended to leave the `metadata.name` empty in the `devfile.yaml` or use [the `new` query parameter](https://www.eclipse.org/che/docs/stable/end-user-guide/url-parameter-for-starting-duplicate-workspaces/). But again, I think that's a distinct issue.

**Comment by l0rd** [comment]
> I can create a distinct issues for non-samples but in general I would ask the user if he wants to restart the existing workspace or replace it with the new one. To create multiple workspace using the same devfile it's recommended to leave the metadata.name empty in the devfile.yaml or use [the new query parameter](https://www.eclipse.org/che/docs/stable/end-user-guide/url-parameter-for-starting-duplicate-workspaces/). But again, I think that's a distinct issue.

@akurinnoy I have changed the title here because it looks that the issue is related to samples only. If that's not the case let's discuss it because the solution is not clear.

**Comment by max-cx** [comment]
Sync'd with Red Hat JIRA https://issues.redhat.com/browse/CRW-3640
