### ISSUE TITLE
403 error, not able to do git push to upstream dashboard branch with https

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21627]
### Describe the bug

On a Che instance with oAuth set up, I'm not able to push branches to https://github.com/eclipse-che/che-dashboard/. 

### Che version

next (development version)

### Steps to reproduce

1. Create a project with this devfile https://github.com/dkwon17/che-dashboard/blob/devfilev2/devfile.yaml
ex:
```
{CHEHOST}/#https://raw.githubusercontent.com/dkwon17/che-dashboard/devfilev2/devfile.yaml
```
2. When the editor starts, run `git checkout -b test-branch`
3. Create a git commit
4. Try to push to the `upstream` remote with `git push upstream test-branch`

This results in the following:
```
bash-4.4$ git push upstream test-branch
remote: Permission to eclipse-che/che-dashboard.git denied to dkwon17.
fatal: unable to access 'https://github.com/eclipse-che/che-dashboard.git/': The requested URL returned error: 403
```

### Expected behavior

Should be able to push to remote

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

I experience this issue in the dogfooding instance

**Comment by vinokurig** [comment]
This is an expected behaiviour because [OAuth App access restrictions](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/about-oauth-app-access-restrictions) are enabled by default in a GitHub organisation.
To request the access:
1. [Review authorized OAuth Apps](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/reviewing-your-authorized-integrations#reviewing-your-authorized-oauth-apps) in your GitHub account page.
2. Find the related oAuth app in the list and click it:
![screenshot-github com-2022 08 16-15_41_19](https://user-images.githubusercontent.com/7668752/184882179-e6aefa7f-ffef-4acb-b439-b9cb9bafbbbd.png)
3. Request access for the `eclipse-che` organization:
![screenshot-github com-2022 08 16-15_43_30](https://user-images.githubusercontent.com/7668752/184882850-7d4dd928-7103-46d6-a8f2-1296618e0b55.png)

**Comment by l0rd** [comment]
Honestly that doesn't seams like a big deal as usually developers fork a GitHub repository and `git push` to their fork rather than to a dedicated branch of the upstream repository.

**Comment by svor** [comment]
It seems there is nothing to fix, can we close the issue and suggest to create a fork and do push commands into that fork?
@vinokurig @dkwon17 WDYT?

**Comment by dkwon17** [comment]
I think we can close this issue, although, the procedure described here https://github.com/eclipse/che/issues/21627#issuecomment-1216592765 would have to be done to make PRs to che-dashboard since at least for now, the PR checks are done only for PRs made from branches on the upstream repo (eclipse-che/che-dashboard)
