### ISSUE TITLE
Existing workspaces can not be started on the dogfooding instance: DevWorkspace storage-type attribute cannot be changed once the workspace has been created.

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21707]
### Is your task related to a problem? Please describe

After adding storage type-related attributes - https://github.com/eclipse-che/che-dashboard/pull/625 
 existing workspaces can not be started: Failed to start the workspace empty-2dm4, reason: Failed to update workspace 'empty-2dm4'. Unable to patch devworkspace: admission webhook "mutate.devworkspace-controller.svc" denied the request: DevWorkspace storage-type attribute cannot be changed once the workspace has been created.

![image](https://user-images.githubusercontent.com/1461122/190626139-ddbde57f-89e1-4a5e-9eda-80a5a3f18a1f.png)

### Describe the solution you'd like

Workspace should be started correctly

### Describe alternatives you've considered

potentially, we should drop the webhook at all, and allow swithing the storage type, but warn the admin somehow that it could lead to the data loss

**Comment by ibuziuk** [comment]
PR has been sent - https://github.com/devfile/devworkspace-operator/pull/927
however, we should consider potentially removing storage webhook entirely

**Comment by ibuziuk** [comment]
@olexii4 one other potential problem that we should avoid is patching DW during startup. I thought that this should have been fixed by https://github.com/eclipse-che/che-dashboard/pull/626
but please do check that we add storage attributes before (not during startup)

**Comment by amisevsk** [comment]
This is still not resolved due to https://github.com/eclipse/che/issues/21714. I've opened DWO PR https://github.com/devfile/devworkspace-operator/pull/932 to workaround the issue for now.

**Comment by l0rd** [comment]
@amisevsk @AObuchow can you please confirm if this issue has been addressed and we can move forward with the release of 7.54.0

**Comment by amisevsk** [comment]
This issue is resolved in DWO `next` in https://github.com/devfile/devworkspace-operator/pull/932 and DWO `v0.16.0` in https://github.com/devfile/devworkspace-operator/pull/933. However, it will be present if DWO v0.15.x and earlier is used, as the webhook is present in those releases. 

The proper fix for this issue would be resolving https://github.com/eclipse/che/issues/21714 in order to not update the storage type for existing workspaces. The workaround we have implemented is to just remove a previously-included webhook that blocks changing the storage type for DevWorkspaces.

I'll close this issue since it's no longer present, and further progress can be tracked in https://github.com/eclipse/che/issues/21714.
