### ISSUE TITLE
Allow specify workspace pods schedulerName via CheCluster spec

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21803]
### Is your task related to a problem? Please describe

There are some specialized Kubernetes scheduler that can improve workspaces performances. One example is [Portworx Stork](https://portworx.com/blog/stork-storage-orchestration-kubernetes/). To use those schedulers pod should reference them in the [`PodSpec.schedulerName` field](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling).

### Describe the solution you'd like

Now it is possible to set arbitrary fields of the workspace Pod and containers and we need a dedicated CR property in Eclipse Che operator for setting the schedulerName:

`spec.DevEnvironments.defaultPodSchedularName`

under the hood, Che operator would propagate this value to the managed DWOC, and set correct value for schedulerName e.g. config.workspace.podSecurityContext.schedulerName: <checluster value> 

### Release Notes Text

Before, the Kubernetes scheduler that managed Che workspaces was always the default one. Now Che administrators can specify an alternative Kubernetes scheduler using the CheCluster custom resource.

**Comment by dkwon17** [comment]
Hi @ibuziuk , I made a PR on the DWO side: https://github.com/devfile/devworkspace-operator/pull/976, but instead of `config.workspace.podSecurityContext.schedulerName`, the PR introduces `config.workspace.schedulerName`, because `schedulerName` is not part of a pod's `podSecurityContext` ([DWOC types](https://github.com/devfile/devworkspace-operator/blob/890b27cba33cfeae081a682279b579ee6aaae4fb/apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go#L147), [corev1 types](https://github.com/kubernetes/api/blob/9e1815a99d4fa3983f39ae3bf1cd68dda5df49da/core/v1/types.go#L3654)), WDYT?

**Comment by dkwon17** [comment]
Fixed thanks to https://github.com/eclipse-che/che-operator/pull/1587

The schedulerName for workspace pods is now configured within `spec.devEnvironments.podSchedulerName` in the Che CR
