### ISSUE TITLE
Activating extension 'anwar.resourcemonitor' failed: Cannot find module 'systeminformation' Require stack

### ISSUE THREAD

**Issue by satyamburhade** [eclipse/che#21815]
### Describe the bug

The "Resource Monitor" extension throws the below error after installation on VScode Dev Spaces v3.2:
```
Activating extension 'anwar.resourcemonitor' failed: Cannot find module 'systeminformation'
Require stack:
- /checode/remote/extensions/anwar.resourcemonitor-1.0.10-universal/out/extension.js
- /checode/checode-linux-libc/out/vs/loader.js
- /checode/checode-linux-libc/out/bootstrap-amd.js
- /checode/checode-linux-libc/out/bootstrap-fork.js.
```

### Che version

7.50

### Steps to reproduce

- Install Dev Spaces v3.2
- Create a VScode workspace (For example NodeJS express VScode)
- Install the "Resource Monitor" extension from the marketplace

### Expected behavior

Extension activated successfully

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by ibuziuk** [comment]
@azatsarynnyy @svor folks, could you please take a look?

**Comment by azatsarynnyy** [comment]
@satyamburhade
A couple of important notes:
- when you install the extension in Che/DS, it's installed from the OpenVSX registry, but not from the MS Marketplace;
- there are `Resource Monitor` extensions present on both registries, but they are different extensions.

The `Resource Monitor` extension [published on the OpenVSX registry](https://open-vsx.org/extension/anwar/resourcemonitor) actually [is a fork](https://github.com/anwar3606/resmon) of the [original extension](https://github.com/Njanderson/resmon) which is [published on the MS Marketplace](https://marketplace.visualstudio.com/items?itemName=mutantdino.resourcemonitor).

I suppose the forked version doesn't contain the fix for the bug you mention. If I install the extension from the OpenVSX registry to my local VS Code I get the same error and it does not work. So, my advice is to file an issue to https://github.com/anwar3606/resmon. BTW, the last change there was 2 years ago, so I'm not sure if it's still maintained.

**Comment by azatsarynnyy** [comment]
I'm closing the issue as it turned out to be an issue with the particular extension which is not included in Che.
