### ISSUE TITLE
Implement health check endpoint for Che-code

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22008]
### Describe the bug

A health check endpoint for Che-code would help solve https://github.com/eclipse/che/issues/21796 and help fix 404 error on workspace startup:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/83611742/219471449-a11d9117-1e20-4a48-94b5-10cf44a4da31.png">

 Dashboard side PR: https://github.com/eclipse-che/che-dashboard/pull/730 helps fix https://github.com/eclipse/che/issues/21796, but it does not solve the root issue.

When a workspace is started with Che-code editor, the DWO operator pings the `/healthz` endpoint to determine if the DW status can be changed from `Starting` to `Running`. For compatibility reasons, if pinging the `healthz` endpoint results in a 4XX error, the DWO operator sets the DW's status to `Running` (on DWO side, see [here](https://github.com/devfile/devworkspace-operator/blob/4ea3d5cd8ef0622cf7883b62e7b782941f174b04/controllers/workspace/status.go#L175-L178)). 

However, there is an issue on workspace startup, where pinging the `/healthz` endpoint results in: `404`, then results in `502` for a few seconds, and then back to `404`.

So:
```
404 -> 502 -> 404
(*)    (**)
 
(**) happens for a few seconds
```

This causes the DW's status to be `Running`, `Starting` and then back to `Running` (at the 20 second mark of the video): 

<details><summary>Video</summary>

https://user-images.githubusercontent.com/83611742/219443471-6fdea8b8-e5cb-43c7-a41e-ba06d682bbda.mov

</details>

This behaviour ultimately causes https://github.com/eclipse/che/issues/21796, since the dashboard tries to direct the user to the editor when the  `/healthz` endpoint results in `404` at `(*)`, but then the request to the DW `mainUrl` fails due to `502` error at `(**)`.

Implementing  the `/healthz` endpoint where 2XX is returned when the vscode server is ready and 503 when it is not, would fix the root cause of https://github.com/eclipse/che/issues/21796

### Che version

Che next

### Steps to reproduce

1. On a clusterbot cluster (`launch 4.12`), deploy Che `next` channel with `chectl server:deploy -p openshift`
2. Open an empty vs code workspace
3. Quite often, the workspace would start but the user would be redirected to either the dashboard, the `workspace is not running` page, or a 404 error page. When this happens the DW's `status.phase` becomes `Starting -> Running -> Starting -> Running`

### Expected behavior

The editor should be opened on workspace startup.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS, other (please specify in additional context)

### Additional context

The issue is reproducible quite easily on clusterbot 4.12

**Comment by RomanNikitenko** [comment]
I created a PR to the Che-Code with changes that allow to serve health check requests: https://github.com/che-incubator/che-code/pull/210.

Unfortunately, it doesn't resolve the original problem: from time to time I still face 404 code on a workspace startup when dashboard opens IDE.

Within my investigation I saw in logs that
- the requests `healthz` really come
- 503 response code is returned while the server is not available
- 200 response code is returned when server is ready to serve requests,
- sometimes workspace status is changed like: `Starting` => `Running` => `Starting`
- if it happens ^ then I get 404 when dashboard tries to open IDE

I asked @amisevsk to help me with debugging DWO --> Che-Code interaction for the `/healthz` requests. Angel has found that:
- in general health check requests work as expected
- but from time to time DWO makes the request and does get a 404 (instead of 503). 
- it looks like the cause of the problem is on the traefik side: https://github.com/traefik/traefik/issues/7347. 

Thanks a lot @amisevsk for your help!

I'm not sure if we can get around this problem somehow on the Che-Code side. Maybe we could provide a workaround on the DWO side - like:
- consider that the endpoint is unimplemented (404) only if DWO has got 404 response code 3 times in a row
or
- implement health check endpoint for the IDEA and change a workspace status only when DWO has got 200 response (do not change the status on the 404 response code)

@l0rd @amisevsk @azatsarynnyy if you have any ideas - please share them

**Comment by amisevsk** [comment]
One (ugly) option might be to use `podSpecOverrides` to add a [liveness/readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) to the pod. We're running into this issue because DWO needs to be flexible in handling the health check since not all main endpoints implement one (and also because traefik is returning 404 for some reason :shrug:).

We might be able to update the editor devfile definitions to specify a HTTP liveness probe for `/healthz` that only marks the pod as running once it returns `200`. This should resolve the issue (and make the DWO check redundant / succeeding on the first try) but might make it impossible for devfiles to specify liveness probes of their own.

**Comment by RomanNikitenko** [comment]
@amisevsk 
thank you for your answer!

I've added a reference for your comment to the new issue: https://github.com/eclipse/che/issues/22163#issuecomment-1513730987
