### ISSUE TITLE
Checode entrypoint fails (undefined symbol: FIPS_selftest)

### ISSUE THREAD

**Issue by meanderix** [eclipse/che#22109]
### Summary

I'm using Che with Openshift DevSpaces and I'm trying to use a custom image (php-based) for the "tools".

I'm getting the following error when `/checode/entrypoint-volume.sh` is bootstrapping VS code:
`/checode/checode-linux-libc/node: symbol lookup error: /checode/checode-linux-libc/node: undefined symbol: FIPS_selftest, version OPENSSL_1_1_0g`

How should this be addressed?

**Comment by amisevsk** [comment]
Hi @meanderix. Since Che runs the code editor within the "tools" container, there are some prerequisites that must be installed for the editor to successfully run. It looks like you might be hitting an issue due to the version of OpenSSL installed in your custom container -- can you share the dockerfile you are using to build the image?

See related issues: https://github.com/eclipse/che/issues/21778, https://github.com/eclipse/che/issues/21629, and potential workaround: https://github.com/che-incubator/che-code/tree/main/build/dockerfiles (these are for UBI9 containers, but it seems a simialr issue you're running into.)

cc: @RomanNikitenko any advice?

**Comment by RomanNikitenko** [comment]
@amisevsk 
I think your assumption is correct, Angel.
So, the workaround should help to resolve the problem.

**Comment by meanderix** [comment]
> can you share the dockerfile you are using to build the image?

We're using docker.io/php:8.1-fpm as the base image. I will try out the suggested links tomorrow.

**Comment by meanderix** [comment]
The same error can be replicated with the image `docker.io/bitnami/minideb:bullseye`.

**Comment by RomanNikitenko** [comment]
@meanderix 
Did you have a chance to try [the workaround](https://github.com/che-incubator/che-code/tree/main/build/dockerfiles)?

<img width="460" alt="Screenshot 2023-04-04 at 09 53 56" src="https://user-images.githubusercontent.com/5676062/229712020-8c0dd3f4-b271-476f-b644-11b4d0fc25af.png">
So:
- install Node.js version >=16.17.x and <17
- provide env variable with path to the Node.js
