### ISSUE TITLE
Add ability to annotate Service Account

### ISSUE THREAD

**Issue by NateLove** [eclipse/che#22134]
### Is your enhancement related to a problem? Please describe

There is a feature in OpenShift to allow pods to interact with AWS resources if configured with the specific annotation on the service account associated with the pod. This would allow developers to deploy and interact with AWS resources without having to login to AWS when using Dev Spaces in this instance.

### Describe the solution you'd like

There is currently a feature which allows annotations for deployments and services through the devfile, the solution I would like is to add a config for adding an annotation to the service account that is created.

**Comment by l0rd** [comment]
[IAM roles for ServiceAccounts AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

Devfile `podOverrides` can be used to annotate Pods but not ServiceAccounts.

Currently ([since v7.58](https://github.com/eclipse/che/releases/tag/7.58.0)) it's possible to using a specific service account per namespace (i.e. per user). The namespaces service accounts can be annotated (manually) and that would address this issue.

Recently ([since v7.64](https://github.com/eclipse/che/releases/tag/7.64.0)) it's possible to [specify a ServiceAccount token volume projection](https://github.com/eclipse/che/issues/22012). That's a [new Kubernetes feature (v1.20)](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection) allowing to federate with external identity provider. But that doesn't look to be helpful for AWS IAM.

A solution to avoid manual creation of the SA and the annotations is adding a new `CheCluster` field, a correponding field in the DWOC and implement the DW controller feature that applies the annotations to the service accounts:

```yaml
spec:
  devEnvironments:
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::111122223333:role/my-role'
```

**Comment by etsauer** [comment]
In AWS, we are using the AWS-built solution for assuming roles. https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by l0rd** [comment]
The solutions that I proposed above (manually specify the SA annotation or specify the annotation in CheCluster CR) don't work for this use case. 

The IAM role is specific to the application (git repository):
- different workspaces of the same developer are supposed to have different IAM roles
- workspaces created from the same repository but by different developers should have the same IAM role

**Comment by l0rd** [comment]
A possible solution to investigate here are AWS Short Lived Credentials:
- https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md
- https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html
