### ISSUE TITLE
How to use the volume across the che worker pods in che version 7.41

### ISSUE THREAD

**Issue by Sathiskumar18** [eclipse/che#22303]
### Summary

Hello All,

We are using multiple docker container in the pods and some docker image has a huge size and we are planning to reduce it.

Hence identified that we are copying the folders into the docker images which makes the size big.

we try to pull that folder from external storage(AWS S3) and that happened every pod initialization and because of it, the pod initialization takes time to load.

I would like the pull that external folder inside the node initialization itself so the other worker pod can make use of it without downloading each.

Can someone suggest a possible way to achieve this?

Note: we are using the older CHE version 7.44.

**Comment by AObuchow** [comment]
@Sathiskumar18 Thank you for the question :) 

> Note: we are using the older CHE version 7.44.

Is there a particular reason why you are using an older version of Che & haven't upgraded?

Which type of Kubernetes cluster (e.g. OpenShift?) are you currently running Che on?

> We are using multiple docker container in the pods and some docker image has a huge size and we are planning to reduce it.
> Hence identified that we are copying the folders into the docker images which makes the size big.

There is a Che-related project called the [Kubernetes image puller](https://github.com/che-incubator/kubernetes-image-puller) which has the purpose of caching container images on the cluster (on individual nodes). At a quick glance, this seems like it would alleviate your difficulty of achieving a quick workspace startup (by already having the large container images downloaded and cached).

Is the root of your problem that downloading the large image size is slow? Or is there another reason why you want to reduce the container image size.

**Comment by Sathiskumar18** [comment]
@AObuchow Thanks for your reply!

We are using the old che version because we didn't get enough bandwidth to upgrade it also we have in the pipeline to do that.

yes when we do the image pull when the workspace startup due to the big size image it's taking more time to pod initialization and looks annoying

Also, the big size of the image increases the build time, and pull time also increases the ECR storage cost.

yes, we are using the open shift Kubernetes cluster in our che.

Could you please brief how the [Kubernetes image puller](https://github.com/che-incubator/kubernetes-image-puller) helps us to fix this issue since we have the imagePullPolicy not always only when the changes found.

**Comment by AObuchow** [comment]
@Sathiskumar18 I apologize for the delay in my response.

> Could you please brief how the [Kubernetes image puller](https://github.com/che-incubator/kubernetes-image-puller) helps us to fix this issue since we have the imagePullPolicy not always only when the changes found.

I had to experiment a bit with the Kubernetes Image Puller as I didn't have any hands on experience with it previously.
From my understanding, the image caching used in Kubernetes is on a per-node basis. Setting `imagePullPolicy: IfNotPresent` will prevent downloading an image if it is already cached on the node in the cluster.

In contrast, the Kubernetes Image Puller will pre-pull the images you desire onto _every_ node, so that each node on the cluster has the image already cached. This should significantly reduce image pull time regardless of which node your workspace starts up on.

To use the Kubernetes image puller:
1. Install Kubernetes image puller (there are instructions on the [README](https://github.com/che-incubator/kubernetes-image-puller#readme) for various installation methods). In my testing, I installed it with OperatorHub from the OpenShift dashboard GUI.
2. Configure your Che Cluster CR instance so that the Kubernetes image puller is enabled, and add your images as a string separated by semicolons. E.g. `kubectl edit checluster -n <ECLIPSE-CHE-NAMESPACE>`

  
```diff
(...)
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard: {}
    devWorkspace: {}
    devfileRegistry: {}
+    imagePuller:
+      enable: true
+      spec:
+        images: 'quay.io/mloriedo/universal-developer-image:ubi8-latest'
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
```

In my example, the `quay.io/mloriedo/universal-developer-image:ubi8-latest` image will now be pulled and cached on all nodes in the cluster.
