### ISSUE TITLE
Empty Workspace failed to start, with error "Disconnected. Attempting to reconnect..", or 502 Bad Gateway error

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22321]
### Describe the bug

Empty workspace failed to start on Eclipse Che Next. 
It showed an error `Disconnected. Attempting to reconnect...` in a minute after the Editor had opened, or stuck on entering VS Code  Editor.

### Che version

7.69@latest

### DevWorkspace Operator version

0.22.0-dev.19+9439f60

### Steps to reproduce

# Go to Eclipse Che dogfooding instance
# Try to create empty workspace from "Dashboard > Create workspace" page

**Case 1**. Editor showed an error `Disconnected. Attempting to reconnect...` in a minute after the Editor had opened.
![247171694-9176b717-de10-4a17-a061-5d717b95346f](https://github.com/eclipse/che/assets/1197777/5e5a0284-bfae-4e52-a9e4-b4c2b4e57f54)

Screencast: 
[screencast-eclipse-che.apps.ocp410.crw-qe.com-2023.06.20-18_23_17.webm](https://github.com/eclipse/che/assets/1197777/cf763419-5aa5-4063-9a54-6e248487a278)

**Case 2**. Start workspace page stuck on entering VS Code Editor because of 502 Bad Gateway error:
![Screenshot from 2023-06-23 18-49-11](https://github.com/eclipse/che/assets/1197777/e964e72d-9c6b-40bb-8be5-8377f2fb2eec)

Screencast: [screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.06.23-18_48_44.webm](https://github.com/eclipse/che/assets/1197777/033a4821-44eb-46f2-a2e4-deec5ad44daa)

### Expected behavior

Empty Workspace has started successfully.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Browser: Google Chrome Version 113.0.5672.63
Mozilla Firefox 107.0

Java Spring Boot workspace has started successfully.

**Comment by amisevsk** [comment]
Issue is a side effect of 
1. The default container added to empty workspaces does not define any resource requirements
2. A recent change in DWO (https://github.com/devfile/devworkspace-operator/pull/1129) improved how resources are handled when merging components (if a resource is unspecified we assume you don't want to suddenly be specified when a component is merged onto it)

The two points above interact with DWO's default memory limit/request to produce a workspace where the Code editor is attempting to run in a container with DWO's default memory limit/request for sidecars, which is too small. A similar issue was encountered with DWO samples that do not specify a memory limit/request and was resolved in https://github.com/devfile/devworkspace-operator/pull/1131

This issue will be fixed by https://github.com/devfile/devworkspace-operator/pull/1134, which changes how defaults are used when merging components.

**Comment by amisevsk** [comment]
https://github.com/devfile/devworkspace-operator/pull/1134 is merged, issue is resolved.
