### ISSUE TITLE
Workspace URL change

### ISSUE THREAD

**Issue by martinelli-francesco** [eclipse/che#22378]
### Summary

Starting with 7.67 the workspace URL has been simplified: https://github.com/eclipse/che/issues/20598
In my scenario a workspace consists of two containers, a web server and a websocket server. The web server hosts a web page with javascript code that computes the websocket server URL by replacing the port and container name. By changing the URL completely, the javascript code fails to calculate the websocket server address.
Unfortunately, I cannot update the images because I cannot force clients to update their images.
Is it possible to customize the URL? For my scenario I just need the old format (a bool in the CR would be fine)

**Comment by l0rd** [comment]
@martinelli-francesco thank you for opening this issue. This is a scenario we didn't though about honestly. I understand that you cannot change the image where the logic to infer the URL is. Would updating the devfiles be an option for you?

@dkwon17 do you have any idea how to solve this?

**Comment by martinelli-francesco** [comment]
Yes, I can update devfiles also for existing workspaces.

**Comment by dkwon17** [comment]
Unfortunately I don't think it's possible without editing the web server image to take into account the new url format

> For my scenario I just need the old format (a bool in the CR would be fine)

That could be implemented without much issue, as the old format code exists in the codebase, and is used if details for the new format cannot be found: https://github.com/eclipse-che/che-operator/blob/923972e91e74fc3f1db4e1e55a41b0f9e5f004eb/controllers/devworkspace/solver/che_routing.go#L356-L365

**Comment by amisevsk** [comment]
Not really helpful in this case, but it's maybe useful for others in the future: all workspaces get a file mounted that can be used to figure out the URL for any endpoint, provided you can parse yaml (we can also mount a json version in the future):

```bash
cat $DEVWORKSPACE_FLATTENED_DEVFILE \
    | yq '.components[].container.endpoints[]? | {name, "url": .attributes."controller.devfile.io/endpoint-url"}'
```
(using [yq](https://github.com/kislyuk/yq) above)

Within the file pointed at by `$DEVWORKSPACE_FLATTENED_DEVFILE`, each container endpoint gets an attribute, `controller.devfile.io/endpoint-url`, that contains the URL for that endpoint as provisioned on the cluster.

**Comment by martinelli-francesco** [comment]
> A bool in the Che CR to use the old format for all workspaces could be implemented without much issue, as the old format code exists in the codebase, and is used if details for the new format cannot be found: https://github.com/eclipse-che/che-operator/blob/923972e91e74fc3f1db4e1e55a41b0f9e5f004eb/controllers/devworkspace/solver/che_routing.go#L356-L365

That would be enough for me.

**Comment by martinelli-francesco** [comment]
Is there a plan for the version of Eclipse Che in which this configuration will be available in the CR?

**Comment by l0rd** [comment]
@martinelli-francesco we had an internal discussion and there is no plan to work on this for a few reasons:
- the previous and current endpoint URL schema should not be considered as an API. The way to retrieve endpoints URLs is using the Kube API or the file `/devworkspace-metadata/flattened.devworkspace.yaml` in the workspaces. On our side we need to improve the documentation because I don't think there is anything about that.
- we want to keep the CR options as minimal as possible: introducing a new option is like exposing a new API that we will need to test and maintain for years. We are really careful before adding new fields and this use case seems like an exception rather then a common request.

That said, if you would like to submit a PR to address this problem and if you are ready to help us maintaining the legacy URLs use case, then we would be happy to review and merge the PR when ready.

One last thing that I don't think we mentioned: there may be a workaround for you problem if you are able to use a long enough workspace or endpoint name in your devfile: https://github.com/eclipse-che/che-operator/pull/1702. I am not sure you can change the endpoint name or the workspace name in your devfiles or if those are hardcoded in the URLs the frontend is using.

**Comment by martinelli-francesco** [comment]
For sure I can change the logic for all new images to take the URLs from /devworkspace-metadata/flattened.devworkspace.yaml

Can you confirm that the official (and stable for the future) way to get the container URLs is to get the path of the flattened.devworkspace.yaml file from the env variable DEVWORKSPACE_FLATTENED_DEVFILE and then the URLs are the values of the controller.devfile.io/endpoint-url field, correct?
