### ISSUE TITLE
total k8s noob here: how do I expose Che to other machines???

### ISSUE THREAD

**Issue by gitwittidbit** [eclipse/che#22380]
### Summary

Please bear with me, I am a total noob when it comes to K8s. I have worked with docker but k8s remains a mystery...

Basically, I just want to deploy Eclipse Che for myself (over the internet). And because, as I understand, one can only host it in k8s, I have set up a Minikube cluster (just one node). I have also deployed the Che server to this cluster but now I seem to have met a dead end.

While everything seems to be up and running just fine, I have no idea how to actually access Che from another machine (even in my local network).

### Relevant information

My Minikube one node cluster is running in a VM with the IP 192.168.50.20. For some reason the Che Url is https://192.168.49.2.nip.io/dashboard/ 

My problem ist that outside of the VM "no one" knows where 192.168.49.2 is supposed to be (therefore, 192.168.49.2.nip.io also does not help). 

I have tried port-forwarding to the VM IP but with little success:

kubectl port-forward --address:0.0.0.0 -n ingress-nginx service/ingress-nginx-controller 8080:80 reacts to incoming requests on 192.168.50.20:8080 but responds with "404"

kubectl port-forward --address:0.0.0.0 -n eclipse-che service/che-dashboard 8080:8080 reacts to incoming requests on 192.168.50.20:8080 but only shows a broken picture link icon and a flashing "loading" but that's it...

Any help appreciated!

**Comment by tolusha** [comment]
Have you look at this?
Does it solve your issue?

https://github.com/eclipse/che/issues/19404#issuecomment-807687234

**Comment by gitwittidbit** [comment]
Thank you tolusha, but I don't think this has the answer that I am looking for. If I understand it correctly, this assumes that Che is actually responding to external requests and only deals with the question of how to get those external requests to reach the machine Che is running on.

My problem is a step before: I don't know how to get Che to respond meaningfully to external requests in the first place.

The questions I am pondering are:

- Do I need to port-forward in order to get Che to listen and respond to external? (In docker I just tell docker which external host port to attach to which internal container port and the container will respond.)
- If I need to port-forward, to which service should I forward the host port? (I have tried with the ingress but with no success at all and I have tried with Che-Dashboard but I only got "Loading" out of it)
- If not, what else do I need to do? Do I need to expose something explicitly, do I need to create something (NodePort, Ingress, LoadBalancer)?

Sorry, if the answers to these questions are so obvious that they are not included in the documentation, but I am totally new to k8s...

**Comment by gitwittidbit** [comment]
okay, I may be a step closer - but only a small one.

So I found that if I port-forward to ingress-nginx I can actually reach the same page I reach when I port-forward to che-dashboard. When I try to access "<host-ip>/dashboard/", I get a 404 but when I try to access "<host-ip>/dashboard" (no trailing "/"), I see the "Loading" page again. So maybe that is already all there is to it?

If so, my new problem is that it keeps saying "Loading" but never finishes loading. 

Any help welcome!

**Comment by amisevsk** [comment]
Minikube in general is intended to run on your local machine, and be accessed from your local machine (e.g. you run minikube on your laptop, and access it from your laptop). While there are ways of exposing your minikube cluster to the network (e.g. as @tolusha linked, by configuring your network to allow access), the generally supported way of running kubernetes not-locally would be to deploy a small cluster to the VM. For this you could look into, for example, https://microk8s.io/ (though note to get it fully set up you would also need the ingress addon: https://microk8s.io/docs/addon-ingress).

Worth noting I haven't done this myself and would be of little help with the install process, but the general issue you are facing is that minikube is only accessible from the VM itself, which is generally by design in minikube. The way to fix this would be to set up a proxy on the virtual machine that proxies requests to the minikube cluster and is accessible from the network -- `kubectl proxy` may be able to do this but I'm not sure.
