### ISSUE TITLE
[Test] Unable to login to Azure DevOps from Jenkins instance in factories tests.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse/che#22440]
### Is your task related to a problem? Please describe

https://github.com/eclipse/che/pull/22366 MR updated factories typescript tests to work correctly with  Azure DevOps git provider. If you run these tests on a machine when you're already signed in to Azure, they will work as expected. But from Jenkins instance it waits for code from SMS.

### Describe the solution you'd like

We need to solve this problem somehow (maybe there are other Azure DevOps authentication options).

### Additional context

Screenshots:

![Selection_181](https://github.com/eclipse/che/assets/7760565/b6ff2b22-80d7-4c75-a0d1-87fadaebe892)

[output (3).webm](https://github.com/eclipse/che/assets/7760565/01284fe0-a1d8-4c34-b2d9-83ce57a1979d)

**Comment by nallikaea** [comment]
Hi, @SkorikSergey 
Thank you for the issue

Anti-bot security because we use third-party services in regression testing. 
The best solution is to use mock tool (emulate of request/response behavior of git provider). This is big fundamental task we are discussing now.
Could you, please, describe temporary solution to automate you want to get for now?

cc @musienko-maxim

**Comment by dmytro-ndp** [comment]
An alternative to manual testing and mock servers could be the running tests within a browser where authorization has already been established with the Git provider's server.
