### ISSUE TITLE
how to disable an extension from `che-code`?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#22455]
### Summary

i'm working with this repo https://github.com/che-incubator/che-code

i want to disable `che-activity-tracker` this extension (https://github.com/che-incubator/che-code/blob/main/code/extensions/che-activity-tracker/README.md)

i commented `'che-activity-tracker/tsconfig.json'`  from `gulpfile.extensions.js` file.
i'm not sure if this is enough to disable the extension.

https://github.com/che-incubator/che-code/blob/main/code/build/gulpfile.extensions.js

please let me know if additional steps has to be done to disable the extension

**Comment by AObuchow** [comment]
@Divine1 Are you building Che Code? That seems like it should work if you're building it yourself, though I haven't tested it.

@dkwon17 might be able to verify this or propose another solution that doesn't requiring re-building Che Code

**Comment by Divine1** [comment]
@dkwon17 thank you for sharing this information.

**Comment by azatsarynnyy** [comment]
Hi @Divine1 
Actually, there's no need to rebuild Che-Code in order to disable an extension.
Open an `Extensions` view and enable a filter for listing the built-in extensions only:

<img width="762" alt="image" src="https://github.com/eclipse/che/assets/1636395/8fa69f55-b239-48ef-bbd5-9711b5cb6f1f">

Select `che-activity-tracker` extension and click `Disable` button. Similar steps for enabling it.

**Comment by Divine1** [comment]
@azatsarynnyy  i wanted this extension to not showup in the che-code editor

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy i wanted this extension to not showup in the che-code editor

in this case, I believe the only way is to build your own assembly with the removed extension
since the built-in extension can't be removed at runtime, but disabled only
