### ISSUE TITLE
Simplify the steps for connecting JetBrains Thin Client to the remote IDEA dev server

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#22493]
### Is your task related to a problem? Please describe

Currently, getting a link to connect to the IDEA Remote Dev Server looks like this:
1. With the help of OpenShift Console or `oc` client open a terminal to the `tools` container and check the `/idea-server/entrypoint-logs.txt` file.
2. Find the dev server link at the top. It looks like:
`Join link: tcp://127.0.0.1:5990#jt=a981d291-6826-46e7-8460-77ec6745864f&p=IU&fp=C067327B446B4D7321850EBC5EFA6FDA9BE37603220E3C84BD61AE209B910CD0&cb=223.7571.182&jb=17.0.5b653.14`.

See more details at https://github.com/eclipse/che/issues/21412#issuecomment-1708651003

We can improve that to provide a much simpler UX.

### Describe the solution you'd like

We can run some node app, in the IDEA Remote Dev Server, that could provide a page with the connection link and instructions for the user on how to connect to a running Workspace from a local JetBrains Thin Client. 
Once an IDEA-based Workspace starts, the Dashboard should redirect to that page.

**Comment by kstevena** [comment]
Hi @azatsarynnyy,
To ease the UX you might want to consider a link with a different URI such as `jetbrains-gateway://` so that if the jetbrains gateway is installed and has setup its own URI handlers it would be smoother as I was describing in the previous [#21412 comment](https://github.com/eclipse/che/issues/21412#issuecomment-1314122848)

Do you envision or think we could get rid of the manual port-forward ? Without it then with a redirect on page load to `jetbrains-gateway://xxxx` it would be a very smooth experience. Unfortunately in previous experiments there was no clean way to expose automatically the tcp or ssh port required for the gateway.

**Comment by azatsarynnyy** [comment]
Hi @kstevena 
thanks for your comment. Yes, relying on a system handler of `jetbrains-gateway://` protocol that's what I was thinking about as well.
As, in my experiments, I use TCP link, I'm using `jetbrains-gateway://connect` just for opening the local Gateway app. I didn't find a way to make a `jetbrains-gateway://connect` link with the parameters from a TCP link.

**Comment by azatsarynnyy** [comment]
Now, once the IDEA dev server is running, the Dashboard forwards the browser to a simple page with detailed instructions for the user to make the flow clearer:

<img width="1099" alt="image" src="https://github.com/eclipse/che/assets/1636395/9265f342-582f-4d23-b521-31b5cc25ded3">

**Comment by azatsarynnyy** [comment]
The demo repo for testing https://github.com/azatsarynnyy/web-nodejs-sample/tree/idea-server-sandbox
