### ISSUE TITLE
Workspace idling in VS Code should not happen if a background process is running

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22523]
### Is your enhancement related to a problem? Please describe

When a user is not interacting with VS Code for more than a given amount of time (specified in checluster `devEnvironments.secondsOfInactivityBeforeIdling`), the workspace get stopped automatically. This can be frustrating as long running task started in the cloud dev environment (i.e. a build or ML task) will be aborted if the user doesn't interact with IDE.

### Describe the solution you'd like

There can be a few options:
1) Configure the VS Code extension [che-activity-tracker](https://github.com/che-incubator/che-code/tree/main/code/extensions/che-activity-tracker) to track also events like `onDidChangeActiveTerminal` or `onDidChangeTerminalState`
2) Introduce a new Devfile attribute to allow disabling workspace idling
3) Introduce a new Devfile attribute to allow avoiding idling if specific processes are running

Option 1) looks the simplest although if the long running process doesn't produce an output the workspace will get idled anyway.

Option 2) disable idling completely for the workspace using the devfile but that may be overkill (we still when the long running task have completed and the user is not active).

Option 3) would be the more effective but require more in intrusive changes (machine-exec and devworkspace-operator) and still require.

### Describe alternatives you've considered

There are a few workarounds to disable idling for a single workspace today:
- [Manually disable che-activity-tracker](https://github.com/eclipse/che/issues/22455#issuecomment-1698898625) after starting a workspace
- Add the env variable `SECONDS_OF_DW_INACTIVITY_BEFORE_IDLING="-1"` in the devfile

**Comment by l0rd** [comment]
[Downstream issue](https://issues.redhat.com/browse/CRW-4861)

**Comment by amisevsk** [comment]
One concern with implementing this is that it might be hard to distinguish between e.g. a long-running task with a purpose (an ML workload, etc.) and a long-running task that is just a non-terminating task (e.g. starting the program for debugging). 

I wonder if it might be possible to add functionality so that commands can enable/disable idling automatically -- for example, you could set a specific command to disable idling until it completes while letting idling occur naturally for other non-terminating commands. This could work similar to finalizers on k8s resources, where if there are any finalizers left, idling does not stop the workspace despite having timed out normally.

**Comment by l0rd** [comment]
> I wonder if it might be possible to add functionality so that commands can enable/disable idling automatically -- for example, you could set a specific command to disable idling until it completes while letting idling occur naturally for other non-terminating commands. This could work similar to finalizers on k8s resources, where if there are any finalizers left, idling does not stop the workspace despite having timed out normally.

Yes that's a good idea too. But if the developer has a the terminal open and a command running in it, we should not idle the workspace. No matter if the command doesn't explicitly disable idling. If that's easy to implement (option n.1) then we should go with it.

**Comment by RomanNikitenko** [comment]
@l0rd
about option 1

> Configure the VS Code extension [che-activity-tracker](https://github.com/che-incubator/che-code/tree/main/code/extensions/che-activity-tracker) to track also events like onDidChangeActiveTerminal or onDidChangeTerminalState

I quickly reviewed the extension
and
it looks like [the extension already tracks both events](https://github.com/che-incubator/che-code/blob/f013b37e04d9169f9316e896c4424af9ef9f49ad/code/extensions/che-activity-tracker/src/extension.ts#L22-L23) (`onDidChangeActiveTerminal` and `onDidChangeTerminalState`)

**Comment by l0rd** [comment]
@RomanNikitenko you are right. Any idea on event triggered when some output is shown in the terminal window?

**Comment by RomanNikitenko** [comment]
> Any idea on event triggered when some output is shown in the terminal window?

I think you ask about [this event](https://github.com/microsoft/vscode/blob/6aa2a71ddd097aaa4930e54a908812a0a77d34e8/src/vscode-dts/vscode.proposed.terminalDataWriteEvent.d.ts#L30). 

I checked that the event is fired for both:
- a terminal
and 
- a task
when data is written to a terminal.

It's added as a proposed API due to problems around performance (see https://github.com/microsoft/vscode/issues/78502#issuecomment-518548517).
