### ISSUE TITLE
Eclipse Che and Keycloak

### ISSUE THREAD

**Issue by AussieScorpio** [eclipse/che#22569]
### Relevant information

My Kubernetes cluster is deployed on VPS servers.

I have an instance of Keycloak and an instance of Eclipse Che. I've created a realm for Eclipse Che in Keycloak and a client secret which is used in the checluster. I've also created a user in Keycloak.

When I navigate to my Eclipse Che using eclipse.mydomain.com, I'm redirected to sso.mydomain.com where I enter my username and password. On submit, I'm redirected to the Eclipse Che dashboard and almost immediately, two notifications come up;

__Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: Unauthorized_

_Danger alert:Failed to fetch the user profile data. Unable to get user profile data: Unauthorized__

I have no ideas where to even start to fix this. All the documentation seems to relate only to OpenShift.

Is there a guide somewhere? Any ideas on how to troubleshoot?

**Comment by tolusha** [comment]
We don't have much documentation about deploying Eclipse Che on k8s.
Currently, we try to collect all available pieces of information into a single issue [1]

[1] https://github.com/eclipse/che/issues/22392

**Comment by AussieScorpio** [comment]
> We don't have much documentation about deploying Eclipse Che on k8s. Currently, we try to collect all available pieces of information into a single issue [1]
> 
> [1] #22392

So, Eclipse Che is a Kubernetes solution that nobody knows how to deploy on Kubernetes? How is anyone actually using this?

**Comment by ibuziuk** [comment]
@AussieScorpio hello, thank you for your interest in the project. You can install Eclipse Che on minikube where dex is used as the identity provider. We do not have documented instructions for deploying Eclipse Che on various cloud providers since the installation process can vary. Basically, vanilla k8s requires [Users' Authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) setup. More details can be found in the docs - https://eclipse.dev/che/docs/stable/administration-guide/supported-platforms/

We are looking for contributions from the community as part of https://github.com/eclipse/che/issues/22392 
We already have the community-contributed blog post for setting up Eclipse Che on Azure that might be helpful - https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html
