### ISSUE TITLE
Auth PKCE

### ISSUE THREAD

**Issue by batleforc** [eclipse/che#22572]
### Summary

I didn't find any issue about it, so here I am. In my current environment, the auth of the Kubernetes Cluster is provided thought Zitadel and, a PKCE auth type project. So does Eclipse Che handle the PKCE auth type ? And is it possible ?

https://datatracker.ietf.org/doc/html/rfc7636

**Comment by ibuziuk** [comment]
hello, thank you for your interest in the project. You can install Eclipse Che on minikube where dex is used as the identity provider. We do not have documented instructions for deploying Eclipse Che on various cloud providers since the installation process can vary. Basically, vanilla k8s requires [Users' Authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) setup. More details can be found in the docs - https://eclipse.dev/che/docs/stable/administration-guide/supported-platforms/

We are looking for contributions from the community as part of https://github.com/eclipse/che/issues/22392 
We already have the community-contributed blog post for setting up Eclipse Che on Azure that might be helpful - https://che.eclipseprojects.io/2022/07/25/@karatkep-installing-eclipse-che-on-aks.html

**Comment by batleforc** [comment]
Hi,
Well, a while later after some experimenting. 
If someone ask the question for the future, no Eclipse Che does not handle PKCE. 
But, in the case of Zitadel, I didn't need to make a huge change, just creating a sub application with client credential but same org.
