### ISSUE TITLE
Allow an admin to specify default commands and default events in CheCluster CR

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22580]
### Is your enhancement related to a problem? Please describe

Today it's possible to specify `..defaultComponents` in CheCluster CR but not default commands, events or parent. It's not possible for instance adding a default preStart event.

### Describe the solution you'd like

The CheCluster devEnvironment should support these new properties: 

```diff
spec:
  devEnvironments:
+    defaultCommands:
+        ...
    defaultComponents:
      ...
+    defaultEvents:
+      ...
+    defaultParent:
+      ...
```

### Additional context

https://github.com/devfile/developer-images/pull/115#issuecomment-1747245613

**Comment by AObuchow** [comment]
I don't think this will be used to resolve this issue, but I figured it's worth mentioning: The DevWorkspaceOperatorConfig supports a default [devworkspace template spec](https://github.com/devfile/devworkspace-operator/blob/main/apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go#L135-L138), that allows configuring components, commands, events, etc.

The problem with leveraging this DWOC field is that it operates at the DevWorkspace level rather than devfile level - no default devfile would be created if this was used. Additionally, there's already existing code in Che-Operator and the UD for the default components field in the Che Cluster CR.

**Comment by l0rd** [comment]
> no default devfile would be created if this was used

Well no devfile is created anyway. When there is no devfile in a git repository the dashboard generates a DW and doesn't expose a devfile to the user. Your suggestion should be a good workaround. But DWOC is kind of non-documented feature.
