### ISSUE TITLE
Git clone with submodules

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#22627]
### Summary

I found this related question on [Issue#8516](https://github.com/eclipse/che/issues/8516), but the link to the example doesn't work anymore. 

Could someone tell me if cloning a repo with submodules through the configurations in a `devfile` is supported? Thank you!

**Comment by l0rd** [comment]
Hi @jorgeadrian93, thanks for reaching out. Things have changed a lot since the issue you have linked and that example doesn't work anymore. Since Eclipse Che 7.74 [git submodules should be cloned automatically](https://github.com/devfile/devworkspace-operator/issues/949). Have you tried with a recent version of Che?

**Comment by jorgeadrian93** [comment]
Hi @l0rd, following up on the Eclipse Che Operator update. I realized that in my OpenShift cluster there are 2 similar operators: 

1. Red Hat OpenShift Dev Spaces, 3.9.0 provided by Red Hat 
![image](https://github.com/eclipse/che/assets/19197341/82be302a-fac1-47c0-8b31-0a41c2e7d1d6)

2. Eclipse Che, 7.76.0 provided by Eclipse Foundation 
![image](https://github.com/eclipse/che/assets/19197341/7e79d738-9ca2-4cb1-93fd-2189e948fc73)


Do you know what the difference is between both operators?

**Comment by l0rd** [comment]
@jorgeadrian93 [differences are documented here](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.9/html/release_notes_and_known_issues/about-devspaces_devspaces#differences-between-devspaces-and-che)
