### ISSUE TITLE
lock a devfile

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#22626]
### Summary

Hello, I didn't find any related question. So here I am. I'm looking for an option to _lock_ a `devfile` and prevent it from being modified by certain folks. 

My use case is: Standardize the development environment for all developers, and consistently patched environment. I mean, spreading updates, security patches, installing new components, etc., but these responsibilities will be handled by some experienced roles and prevent being modified for new developers. 

Thank you in advance!

**Comment by l0rd** [comment]
There a few options that I have listed below. But there is no way to completely prevent a developer to customize his development environment (i.e. adding a predefined command, adding an environment variable or changing the memory or cpu request).

1. [Referencing a parent devfile](https://devfile.io/docs/2.2.1/referring-to-a-parent-devfile) from the repository devfile (I have an example [here](https://github.com/l0rd/inventory-quarkus/blob/parent/.devfile.yaml) and all components are defined in [the parent that is not in the repo](https://gist.githubusercontent.com/l0rd/e6d0a4967d3652ec687f76c0e3fbfad9/raw/parent-devfile.yaml)): this allow you to centrally patch and update the images used in the dev environments.
2. Configure the `devEnvironments.defaultComponents` in the [CheCluster CR](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.74.0) so that all the devtools are there and developer don't need to customize their development environments.
3. Configure developers namespace [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/) and [Resources Quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) to prevent arbitrary usage of CPU/memory/storage.
4. Run Che in a Kubernetes cluster that can pull images from a container repository that you control. That prevent developers from using random DockerHub images.

**Comment by jorgeadrian93** [comment]
Noted, Thanks for the help @l0rd
