### ISSUE TITLE
Error `Route and path matches, but all pods are down`  at workspace startup 

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22641]
### Describe the bug

<img width="1260" alt="image" src="https://github.com/eclipse/che/assets/606959/03eeedda-96ad-422d-a929-ba3c0165f7fc">

### Che version

7.75@latest

### Steps to reproduce

I am not able to reproduce this systematically. It happens from time to time on dogfooding instance starting a workspace. Clicking "retry" makes it work.

### Environment

Dogfooding instance

**Comment by l0rd** [comment]
@amisevsk @ibuziuk @tolusha do you have any clue why this can happen?

**Comment by tolusha** [comment]
What about events?

**Comment by amisevsk** [comment]
Are there any issues with the Che Gateway deployment (logs, restarting pods, etc.)? 

I think that's the HTML for the "Application not running" page OpenShift shows when the route doesn't find any deployments.

**Comment by l0rd** [comment]
Could it be that's VS Code that's ready before the gateway? I don't have logs / events but I will get them if I am able to reproduce this problem.

**Comment by dkwon17** [comment]
This issue came from a failed `server-config` request, which is made by the dashboard [here](https://github.com/eclipse-che/che-dashboard/blob/ba7b93da85d6ae5044686cbfb8e14519e7c05994/packages/dashboard-frontend/src/store/ServerConfig/index.ts#L54). I did create this PR: https://github.com/eclipse-che/che-dashboard/pull/1039 but it doesn't deal with the root problem.

@amisevsk is correct, the error message is the HTML page for the "Application not running" page OpenShift shows when the route doesn't find any deployments.

This particular issue is rare and intermittent, and I think it can potentially happen when making any request to che-gateway.

For example, today I got the same error when I was accessing the dashboard, when the dashboard was getting resources:
![image](https://github.com/eclipse/che/assets/83611742/67cb7180-a202-4f3b-a076-e331f703b6d6)

I didn't see anything suspicious in the gateway logs, or events.

We could try enabling [ingress access logs](https://docs.openshift.com/container-platform/4.14/networking/ingress-operator.html#nw-configure-ingress-access-logging_configuring-ingress) and see if that might provide more details

**Comment by dkwon17** [comment]
I believe we can close this issue thanks to the merge of https://github.com/eclipse-che/che-dashboard/pull/1039,

If I can reproduce the issue in https://github.com/eclipse/che/issues/22641#issuecomment-1892841693 again, I will create a new issue
