### ISSUE TITLE
Pull Request Checks fail for the Che-Code when a PR is created from a fork

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22660]
### Describe the bug

I've created a pull request to the Che-Code from a fork.
The `Pull Request Check - Dev` job fails on the `Login to Quay.io` step.
See https://github.com/che-incubator/che-code/actions/runs/6794116398/job/18470022496?pr=292

### Che version

7.75@latest

### Steps to reproduce

1. Create a pull request to the `Che-Code` from a fork.
2. See the corresponding job

### Expected behavior

`Login to Quay.io` step should be successful for the `Pull Request Check - Dev` job

### Additional context

I'm not sure, but maybe the cause of the problem came from the recently merged PR https://github.com/che-incubator/che-code/pull/253

@vitaliy-guliy 
could you take a look?

**Comment by vitaliy-guliy** [comment]
I do not know how it was working till yesterday, but as it described in the article below, ' secrets are not passed to the runner when a workflow is triggered from a forked repository.'

https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow

**Comment by RomanNikitenko** [comment]
could you try to revert your changes and check it?

**Comment by vitaliy-guliy** [comment]
I see there is only way is specify a separate job to push images like it was before
https://github.com/che-incubator/che-code/blob/7.76.0/.github/workflows/pr-check-image-publish.yml

**Comment by azatsarynnyy** [comment]
> I see there is only way is specify a separate job to push images like it was before https://github.com/che-incubator/che-code/blob/7.76.0/.github/workflows/pr-check-image-publish.yml

yes, we should separate the jobs for building and publishing Che-Code test images:
- In the Workflow that is [triggered `on: [pull_request]`](https://github.com/che-incubator/che-code/commit/6d478826a3ca051e6eaf5dec450850c2347834a8#diff-e76e5134b85a9eb3e0d9ce8e671ce97c8c577ff3c24162c45d71691078201347L10-L13), we should run the build jobs only. It allows running it on the PRs opened from the forked repos.
- In the Workflow that is [triggered on completing the previous ^^ one](https://github.com/che-incubator/che-code/commit/6d478826a3ca051e6eaf5dec450850c2347834a8#diff-c4ac243baf2bcf396d1c59aa08aa0de4bf169aa9ebc155809cfb172faac50dc9L10-L16), we can push the images to quay. Such a job will fail on a PR opened from a fork, but it will not block the PR from merging as such a job is not a required PR status check.

I suggest returning to the state of Che-Code GH Workflows that we have before merging https://github.com/che-incubator/che-code/commit/6d478826a3ca051e6eaf5dec450850c2347834a8
Now, it's clearer why we used to have two GH Workflows instead of a single one 🙂

**Comment by azatsarynnyy** [comment]
> Che-dev image appeared to be large (more than 2.5 gigabytes) to be used in artifacts to share the images between jobs.

@vitaliy-guliy doesn't [this step](https://github.com/che-incubator/che-code/commit/6d478826a3ca051e6eaf5dec450850c2347834a8#diff-c4ac243baf2bcf396d1c59aa08aa0de4bf169aa9ebc155809cfb172faac50dc9L51-L70) fix the problem? 
I don't know for sure, but I suppose it may help.

**Comment by vitaliy-guliy** [comment]
> > Che-dev image appeared to be large (more than 2.5 gigabytes) to be used in artifacts to share the images between jobs.
> 
> @vitaliy-guliy doesn't [this step](https://github.com/che-incubator/che-code/commit/6d478826a3ca051e6eaf5dec450850c2347834a8#diff-c4ac243baf2bcf396d1c59aa08aa0de4bf169aa9ebc155809cfb172faac50dc9L51-L70) fix the problem? I don't know for sure, but I suppose it may help.

It increases only the swap file size.
We do not need it as it is possible to build the images without touching the swap.

**Comment by vitaliy-guliy** [comment]
A pull request fixing the problem has been merged
