### ISSUE TITLE
Restart workspace from local devfile sometime fails with 'you have already one workspace running'

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22769]
### Describe the bug

Restart workspace from local devfile sometime fails with 'you have already one workspace running'

### Che version

7.80@latest

### Steps to reproduce

1. open workspaces.openshift.com
2. start a workspace - https://github.com/redhat-developer-demos/northwind-traders
3. update devfile and restart from local devfile
4. ERROR
<img width="796" alt="Screenshot 2024-01-17 at 12 31 05" src="https://github.com/eclipse/che/assets/1461122/e610df71-9831-42f6-970d-0955d914bf50">

### Expected behavior

workspace started without error

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

I believe we need to check that previous workspace is properly stopped before doing the restart

**Comment by vitaliy-guliy** [comment]
The bug is continuously reproducible on workspaces.openshift.com despite I've added checking for a workspace status (see the pull request https://github.com/che-incubator/che-code/pull/331)

To test:
- go to workspaces.openshift.com
- create a workspace using https://github.com/vitaliy-guliy/vscode-test-extension?che-editor=https://gist.githubusercontent.com/vitaliy-guliy/8fbbfafa1de2448acffa01e1386f1a3f/raw/92212202af6d65625a4f13ab40b4e486fd3803d0/editor.yaml
- run Restart workspace from local devfile command

**Comment by ibuziuk** [comment]
@vitaliy-guliy can we close the issue now since https://github.com/che-incubator/che-code/pull/331 has been merged?
