### ISSUE TITLE
Can not revoke Authorization - OAuth token for user was not found

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22776]
### Describe the bug

Can not revoke Authorization - OAuth token for user was not found

### Che version

7.80@latest

### Steps to reproduce

<img width="1383" alt="Screenshot 2024-01-19 at 12 58 29" src="https://github.com/eclipse/che/assets/1461122/0c19c778-9723-4376-a788-93836a058622">

### Expected behavior

Authhorization is revoked without errors

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by akurinnoy** [comment]
From what I see, the dashboard works as expected. It uses the che-server API to revoke tokens for the selected provider. Thus, the dashboard does nothing with OAuth tokens.

![Screenshot 2024-01-19 at 15 17 37](https://github.com/eclipse/che/assets/16220722/7334c5d3-aa12-4088-b419-949bed32e55f)

**Comment by ibuziuk** [comment]
@vinokurig please, take a look at the screencast since I'm not sure PR is addressing the issue I'm facing:


https://github.com/eclipse/che/assets/1461122/94a72e91-0b78-4a57-b88c-ecb04e832435

**Comment by vinokurig** [comment]
@ibuziuk 
I managed to reproduce the issue only with specific conditions:
1. Go to the GitServices tab and see that the authorisation has the green icon which means that it is authorised.
2. Open a new browser tab and manually revoke the authorisation in the [GitHub authorised applications settings page](https://github.com/settings/applications).
3. Switch back to the dashboard tab and revoke the authorisation.

See: the error appears but it is fixed with the PR.
Did you use another use-case to reproduce the bug?
