### ISSUE TITLE
'Unknown provider' error when Sign in to use Github Copilot Chat extension  

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22781]
### Describe the bug

I was able to install the extension (see my screenshot below in the `Additional context` section), but I got the following error when `Sign in` to use Github Copilot Chat extension:

<img width="527" alt="image" src="https://github.com/eclipse/che/assets/5676062/e0268bed-fc92-458c-9e2d-8c0fed170d29">
  

### Che version

7.80@latest

### Steps to reproduce

1. Install `Github Copilot Chat ` VS Code extension
2. Click `Sign In` button
3. The corresponding functionality doesn't work, see https://docs.github.com/en/copilot/github-copilot-chat/using-github-copilot-chat-in-your-ide
4. See errors in browser console

### Expected behavior

It's possible to Sign in and use `Github Copilot Chat ` VS Code extension

### Additional context

I reproduced it on the dogfooding instance

<img width="1248" alt="image" src="https://github.com/eclipse/che/assets/5676062/4cd5446b-85ff-4c98-9c18-b250d46b2b83">

**Comment by vitaliy-guliy** [comment]
The first question, how did you install the extension as it is not published to Open VSX?
Did you use a .vsix file?

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
- yes, I used vsix way to install the extension
- you can see installed version on the screenshot:  `v0.12........`

**Comment by vitaliy-guliy** [comment]
Potentially depends on https://github.com/microsoft/vscode/issues/205592

**Comment by vitaliy-guliy** [comment]
### Workaround for workspaces without fixes in [pull request](https://github.com/che-incubator/che-code/pull/339)

If you try to install the extensions in che-code from the main branch, the copilot chat extension will not work because it cannot get GitHub session due to specific call of the extension plugin API like here
https://github.com/vitaliy-guliy/vscode-test-extension/blob/get-session/src/extension.ts#L39

If `silent` is true, user will not be asked to permit giving the access to his account to the extension. And as result the extension will have `undefined` instead of a session.

If you apply this fixup, it will update your browser database and granted the access for Pull Request extension and for both Copilot extensions.

How to test:
- on the dogfooding instance open the browser console, go to Application tab and remove all what you have in IndexedDB
- create any workspace
- copy the script below, open the browser console again, go to Console tab, paste the script, replace 'vitaliy-guliy' on your github login and execute the script
- remove existing Device Authentication token and authorize again
- reload the page
- install pull request extension, copilot and copilot-chat extensions in exact sequence
- everything should work now

Just to check this workaround is working, try to repeat above steps but do not launch the script.

```javascript
(async function update() {
    try {
        const accountName = 'vitaliy-guliy';
        console.log(`> updating rules for ${accountName}`);

        const req = indexedDB.open('vscode-web-state-db-global');
        await new Promise((r) => (req.onsuccess = r));

        const transaction = req.result.transaction('ItemTable', "readwrite");
        const store = transaction.objectStore('ItemTable');

        const keys = store.getAllKeys();
        await new Promise((r) => (keys.onsuccess = r));

        let rules = [];
        let usages = [];

        if (keys.result.includes(`github-${accountName}`)) {
            const value = store.get(`github-${accountName}`);
            await new Promise((r) => (value.onsuccess = r));
            rules = JSON.parse(value.result);
        }

        if (keys.result.includes(`github-${accountName}-usages`)) {
            const value = store.get(`github-${accountName}-usages`);
            await new Promise((r) => (value.onsuccess = r));
            usages = JSON.parse(value.result);
        }

        const ensureRule = function (extensionId, name) {
            if (rules.find(rule => rule.id === extensionId)) {
                console.log(`> rule for ${extensionId} already exists`);
            } else {
                console.log(`> add rule for ${extensionId}`);
                rules.push({
                    "id": extensionId,
                    "name": name,
                    "allowed": true
                });
            }

            if (usages.find(usage => usage.extensionId === extensionId)) {
                console.log(`> usage for ${extensionId} already exists`);
            } else {
                console.log(`> add usage for ${extensionId}`);
                usages.push({
                    "extensionId": extensionId,
                    "extensionName": name,
                    "lastUsed": Date.now().toString()
                });
            }
        };

        ensureRule('github.copilot', 'GitHub Copilot');
        ensureRule('github.copilot-chat', 'GitHub Copilot Chat');

        const putRules = store.put(JSON.stringify(rules), `github-${accountName}`);
        await new Promise((r) => (putRules.onsuccess = r));

        const putUsages = store.put(JSON.stringify(usages), `github-${accountName}-usages`);
        await new Promise((r) => (putUsages.onsuccess = r));

        console.log('> done');

        await new Promise((r) => setTimeout(r, 1000));
        window.location.reload()
    } catch (e) {
        console.error(e, e.trace);
    }
})();
```
