### ISSUE TITLE
Can't build plugin registry on the dogfooding instance

### ISSUE THREAD

**Issue by svor** [eclipse/che#22918]
### Describe the bug

It's not possible to build plugin registry image on doggfooding instance. The error message is **no space left on device**:
```
ERRO[0062] error deleting build container "d0313f27de952575f60db71659b2710db32e29d47990d62854706af3c542d1af": identifier is not a container 
Error: identifier is not a container: preparing container for next step: creating build container: creating container: creating read-write layer with ID "dd8750be8985f4742d377f7d804f61861d298cb0e57cf732c64057fd63709d98": **no space left on device**
```

### Che version

next (development version)

### Steps to reproduce

1. Start a ws from https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#/https://github.com/redhat-developer/devspaces/tree/sv-fix-devfile
2. Run "5. Build" command

### Expected behavior

The image should be built

### Runtime

OpenShift

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2024 04 12-13_35_27](https://github.com/eclipse-che/che/assets/1271546/692df8cc-eb0f-4f1c-b18f-f9a031131e86)

### Installation method

chectl/next

### Environment

Linux

**Comment by svor** [comment]
@ibuziuk @dkwon17 when I change storage type to **Ephemeral**, the image could be built without errors. 
By default I have storage type **Per-workspace**

**Comment by ibuziuk** [comment]
@dkwon17 could you please comment? is it related to https://github.com/eclipse-che/che/issues/22914 ?

**Comment by dkwon17** [comment]
It's not related to https://github.com/eclipse-che/che/issues/22914, we are running into this issue because persistent user home is enabled, and because images are stored in the home directory where space is running out.

I noticed building the plugin registry image requires about 17GB, while the PVC for the workspace only has the default 5GB.

There are a few solutions to make the build work:
* Change the storagetype to `Ephemeral`
* Introduce a very large volume specifically for the images ([example](https://github.com/dkwon17/devspaces/blob/fae3544409819f908cbf698262a64e025106f88c/.devfile.yaml#L23-L25))
* Use [fuse overlay](https://eclipse.dev/che/docs/stable/administration-guide/configuring-fuse/) to decrease the stored image layer sizes (this is not configured on the dogfooding cluster yet)
* Try to edit the `~/.config/containers/storage.conf` file to change the graphroot directory to another directory outside of the home directory

**Comment by svor** [comment]
@dkwon17 thank you for the information
`Ephemeral` storage type works for me
I've tried to set a volume 35Gi and 40Gi, but the build was failed:
 
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2024 04 16-14_26_58](https://github.com/eclipse-che/che/assets/1271546/c9ca55a5-52f5-4607-b9bf-697310901490)

what I don't understand why it used to work before and now it doesn't

**Comment by dkwon17** [comment]
I think it stopped working recently because we have persistent home enabled and per-workspace persistent home was fixed recently: https://github.com/devfile/devworkspace-operator/pull/1241

**Comment by AObuchow** [comment]
> I think it stopped working recently because we have persistent home enabled and per-workspace persistent home was fixed recently: [devfile/devworkspace-operator#1241](https://github.com/devfile/devworkspace-operator/pull/1241)

This is also what I believe caused this issue to arise. Previously, the $HOME directory where the graphroot directory resides was ephemeral, until persistent $HOME was fixed for per-workspace storage.

**Comment by dkwon17** [comment]
Another option is to define an ephemeral volume for `/home/user/.local`:
https://github.com/dkwon17/devspaces/blob/ce03e4acafc880c063e441202eff12ef40e330d4/.devfile.yaml#L23-L25

**Comment by svor** [comment]
problem was resolved by updating devfile, now it's possible to build the plugin reg in dogfooding instance
