### ISSUE TITLE
Always fetch raw devfiles from the dashboard

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22927]
### Is your enhancement related to a problem? Please describe

Right now, the dashboard can only get raw devfiles from registries (defined in CR). The che-server is responsible for resolving all other URLs. But the che-server can't resolve some raw devfile URLs, like [https://registry.devfile.io/devfiles/dotnet60/1.0.3](https://registry.devfile.io/devfiles/dotnet60/1.0.3).

### Describe the solution you'd like

The dashboard should try to get the data from a URL and determine if it is a raw devfile. If it isn't, it should use the che-server API to resolve the URL.

### Additional context

https://github.com/eclipse-che/che-website/pull/98#issue-2246410666

**Comment by ibuziuk** [comment]
@akurinnoy @vinokurig smth. to discuss before the next sprint planning
currently I'm not convinced that dashboard should handle raw devfiles e.g. the fix might be on che-server side to support URLs like https://registry.devfile.io/devfiles/dotnet60/1.0.3 (I suspect it does not work atm due to missing `.devfile` in the path)

**Comment by akurinnoy** [comment]
fixed by https://github.com/eclipse-che/che-server/pull/683
