### ISSUE TITLE
how install with yaml on the Kubernetes

### ISSUE THREAD

**Issue by fwasdfw** [eclipse/che#22996]
### Summary

hi, i want to build Eclipse Che on my self Kubernetes (LAN network without internet) without helm， but i don't know how should i prepare and get the yaml for install this software. can you tell me the location for install yaml, and whether need postgresql and minIO ?

### Relevant information

Kubernetes is 1.21.0

**Comment by tolusha** [comment]
Hello @fwasdfw 
That's a tricky question since we don't have documented procedure how to deploy Eclipse Che on disconnected Kubernetes cluster. We do have such a procedure for OpenShift only [1]. 

I would say that you need a private docker registry and you don't need any PostgreSQL DB. Here are yamls to deploy DevWorkspace and Che operators [2] [3]. Also you have to configure OIDC provider on the cluster.

[1] https://eclipse.dev/che/docs/stable/administration-guide/installing-che-in-a-restricted-environment/
[2] https://github.com/devfile/devworkspace-operator/tree/main/deploy/deployment/kubernetes
[3] https://github.com/eclipse-che/che-operator/tree/main/deploy/deployment/kubernetes
[4] https://eclipse.dev/che/docs/stable/administration-guide/installing-che/

**Comment by fwasdfw** [comment]
> 你好@fwasdfw 这是一个棘手的问题，因为我们没有记录源断开连接的 Kubernetes 集群上部署 Eclipse Che 的过程。我们确实自主研发了 OpenShift 的过程 [1]。
> 
> 我想说的是，你需要一个私有的 Docker 常见问题解答，而不需要任何 PostgreSQL DB。以下是用于部署 DevWorkspace 和 Che 管理员的 yaml [2] [3]。你还必须在服务器上配置 OIDC 提供程序。
> 
> [1] https://eclipse.dev/che/docs/stable/administration-guide/installing-che-in-a-restricted-environment/ [2] https://github.com/devfile/devworkspace-operator/tree/main/deploy/deployment/kubernetes [3] https://github.com/eclipse-che/che-operator/tree/main/deploy/deployment/kubernetes [4] https://eclipse.dev/che/docs/stable/administration-guide/installing-che/

@tolusha so, should i install the che-server in my k8s also？

**Comment by fwasdfw** [comment]
@tolusha so, should i need install the che-server in my k8s also ?

**Comment by AObuchow** [comment]
@fwasdfw Correct, you'll need to install the che-operator (I believe that's what you meant by che-server? or were you referring to the specific che-server component?), which manages deploying all of the components of Che with the exception of the DevWorkspace Operator, which you'll have to deploy yourself.

**Comment by fwasdfw** [comment]
i'd discarded
