### ISSUE TITLE
Ollama sample failed to start

### ISSUE THREAD

**Issue by svor** [eclipse/che#23193]
### Describe the bug
The Ollama sample failed to start on the dogfooding instance:

![screenshot-raw_githubusercontent_com-2024_10_11-14_57_15](https://github.com/user-attachments/assets/6873ecdb-ab07-4bab-b444-83b797f54f31)

It seems something wrong with `postStart` [commands](https://github.com/devfile/registry/blob/main/stacks/ollama/devfile.yaml#L62C3-L65):
```
events:
  postStart:
    - pullmodel
    - pullautocompletemodel
    - copyconfig
```

### Che version

next (development version)

### Steps to reproduce

Create a workspace from ollama sample in Che dogfooding instance

### Expected behavior

Workspace should start

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by RomanNikitenko** [comment]
@svor 
I was able to start a workspace for the sample

<img width="922" alt="image" src="https://github.com/user-attachments/assets/40da6cb3-97ae-467b-a233-2f81f863421b">

**Comment by azatsarynnyy** [comment]
And it works well with the thin lama stack (embedded)
I can reproduce the issue with the thick lama stack (devfile.io)
<img width="545" alt="image" src="https://github.com/user-attachments/assets/739355f1-d480-4bb3-80cf-50603de0fadc">

**Comment by ibuziuk** [comment]
Looks like the culprit is related to the storage configuration on the dogfooding:

```
    storage:
      perWorkspaceStrategyPvcConfig:
        claimSize: 5Gi
      pvcStrategy: per-workspace
```

On Developer Sandbox where the sample works, it requires 6.5 Gi

<img width="424" alt="Screenshot 2024-10-14 at 16 16 58" src="https://github.com/user-attachments/assets/bc8955c1-afd0-417a-be55-239e9081f3d0">

I bumped the storage config to 7Gi on dogfooding, which resolved the issue.
